import type { OfficialSource } from "./types";

export const OFFICIAL_SOURCES: readonly OfficialSource[] = [
  {
    id: "cliptop-blumotion-full",
    title: "CLIP top BLUMOTION 完整铰链系列",
    url: "https://publications.blum.com/2022/catalogue/zh/186/",
    summary:
      "CLIP top BLUMOTION 是 Blum 铰链系列中集成阻尼闭合功能的高端解决方案。系列包含罩杯门（全盖）、半盖门（半盖）、无盖门（嵌入）三种基础盖位类型，另有宽门铰链和转角铰链等特殊变体。标准孔距为 45mm，底座高度有 0mm（无间隙）、9mm（标准）、18mm（宽间隙）三种；开合角度覆盖 95°、110°、155°，其中 155° 超大角度铰链适合衣柜大开门应用。BLUMOTION 阻尼机构内置于铰链罩杯内，可在面板重量 5kg~50kg 范围内实现轻柔无冲击关闭。调节范围：三维调节中高度 ±2mm、左右 ±2mm、深度 +3mm/-2mm。该系列均采用 CLIP 快装技术，铰链臂通过卡扣安装，拆装无需工具。适用门厚范围为 15~32mm，支持木质门和铝合金门，可广泛用于厨房、衣柜、浴室柜及办公家具。",
    official: true,
    keywords: [
      "clip top blumotion",
      "全盖",
      "半盖",
      "无盖",
      "宽门铰链",
      "转角铰链",
      "155度铰链",
      "超大角度",
      "blumotion阻尼",
      "clip安装",
      "罩杯门",
      "三维调节",
      "快装",
      "铰链",
      "合页",
      "门铰",
    ],
  },
  {
    id: "cliptop-nondamp",
    title: "CLIP top 无阻尼铰链系列",
    url: "https://publications.blum.com/2022/catalogue/zh/188/",
    summary:
      "CLIP top 无阻尼版是 CLIP top 系列的入门级产品，与 CLIP top BLUMOTION 共享相同的安装尺寸体系和 CLIP 快装结构，但未内置 BLUMOTION 阻尼机构。底座型号包括 173H7100（0mm 间隙）、173H7109（9mm 间隙）、173H710E（18mm 间隙）等。孔距 45mm，开合角度涵盖 95°、110°、120° 三个规格。适用门厚 15~32mm，支持 3~5mm 门缝调节。该系列提供镀锌和镍饰面两种表面处理，适合预算有限的标准柜门应用场景，或作为需要另行搭配外部阻尼合页的方案。",
    official: true,
    keywords: [
      "clip top",
      "无阻尼",
      "无BLUMOTION",
      "标准铰链",
      "基础铰链",
      "cliptop",
      "铰链",
      "合页",
      "柜门",
      "门盖",
      "门铰",
      "入门级",
      "经济型",
      "clips",
      "快装",
    ],
  },
  {
    id: "modul-hinge",
    title: "MODUL 铰链系列",
    url: "https://publications.blum.com/2022/catalogue/zh/190/",
    summary:
      "MODUL 是 Blum 铰链系列中定位为窄边框和高性价比的解决方案，主要面向标准橱柜和家具制造。MODUL 铰链的孔距为 45mm，开合角度标准为 95°，另有 110° 可选。该系列同样采用 CLIP 快装结构，与 CLIP top 系列共享底座系统。罩杯直径 35mm，深度 11.5mm；适用门厚 15~24mm，适用门宽上限为 900mm（超过此宽度建议使用双铰链或加宽门铰链）。表面处理为镀锌，承重能力在双铰链配置下最高达 30kg。该系列适合经济型家具项目和对成本敏感的标准柜门安装场景。",
    official: true,
    keywords: [
      "modul",
      "modul铰链",
      "窄边框",
      "标准柜",
      "cliptop",
      "孔距45mm",
      "经济型",
      "性价比",
      "铰链",
      "门铰",
      "clips",
      "快装",
      "35mm罩杯",
      "标准铰链",
    ],
  },
  {
    id: "tip-on-doors",
    title: "TIP-ON for Doors 碰碰开门系统",
    url: "https://publications.blum.com/2022/catalogue/zh/192/",
    summary:
      "TIP-ON for Doors 是 Blum 专为无拉手柜门设计的按压式开门触发机构，原理为通过按压门板前缘触发内部弹簧机构，使门板在气压支杆或扭力弹簧作用下弹出。触发压力需求为 7~10N（约 700~1000gf），适用门重范围为 8~40kg（铰链配置数量需随门重增加：门重 8~15kg 用 2 个铰链，15~25kg 用 2 个加辅助定位，25~40kg 用 3 个铰链）。面板弹出距离为 10~35mm，取决于门板重量和安装角度。该系统可与 CLIP top BLUMOTION 铰链组合使用，实现按压开门和轻柔关闭的双重功能。安装时需确保门面与柜体侧板间隙 ≥ 2mm，且门面与台面高度差 ≤ 3mm 以保证触发灵敏度。适用于厨房吊柜、衣柜和对开门等多种无拉手应用场景。",
    official: true,
    keywords: [
      "tip-on",
      "碰碰开",
      "按压开门",
      "无拉手",
      "push-to-open",
      "碰触开门",
      "免把手",
      "气压支杆",
      "弹簧弹出",
      "无把手",
      "触发压力",
      "柜门开启",
      "tipon",
      "无把手设计",
      "门面间隙",
    ],
  },
  {
    id: "hinge-3d-adjustment",
    title: "Blum 铰链三维调节与盖位指南",
    url: "https://publications.blum.com/2022/catalogue/zh/194/",
    summary:
      "Blum CLIP top 铰链的三维调节功能是实现门板精确对齐的关键。高度调节（上下）：通过偏心螺丝实现，范围 ±2mm，用于对齐上下门缝，适用于所有盖位类型（0 盖全盖、1 盖半盖、2 盖内嵌）。左右调节（左右）：通过底座侧边螺丝实现，范围 ±2mm，用于对齐左右门缝和双门中缝。深度调节（前后）：通过铰链臂深度调节螺丝实现，范围 +3mm/-2mm，用于控制门板与柜体侧板的相对位置，解决门板内外凸出问题。盖位调节：0 盖（无间隙罩杯）适合两扇门关闭后齐平效果；1 盖（半盖罩杯）适合中缝对开门；2 盖（无盖嵌入罩杯）适合将门板嵌入柜体框架内的应用。不同盖位调节范围略有差异，安装前应确认所需盖位类型。",
    official: true,
    keywords: [
      "三维调节",
      "高度调节",
      "深度调节",
      "左右调节",
      "盖位调节",
      "0盖",
      "1盖",
      "2盖",
      "全盖",
      "半盖",
      "内嵌",
      "门缝调节",
      "双门对齐",
      "偏心螺丝",
      "铰链安装",
      "clip top调节",
    ],
  },
  {
    id: "hinge-selection-params",
    title: "Blum 铰链选型参数指南",
    url: "https://publications.blum.com/2022/catalogue/zh/194/",
    summary:
      "Blum 铰链选型需综合考虑门厚、门宽、门高、开门角度和承重五个核心参数。门厚：标准范围 15~32mm，木质门建议 ≥ 16mm，铝合金门 ≥ 18mm。门宽：单扇门宽 ≤ 900mm 时用 2 个铰链，900~1200mm 时用 3 个铰链，超过 1200mm 建议使用宽门铰链或加强型方案。门高：门高超过 2000mm 时，铰链数量需在标准基础上增加 1 个。开门角度：标准柜门 95°~110°，衣柜大开门需 155° 超大角度铰链，窄边柜需 45° 或 30° 小角度铰链。承重计算：每个 CLIP top BLUMOTION 铰链在标准安装深度（35mm 底座）下承载能力约 15kg，实际承重 = 铰链数量 × 单个承重 × 安装系数（系数 0.85~0.95，视安装精度而定）。门重超过 40kg 时建议使用加强型底座或加装支撑配件。",
    official: true,
    keywords: [
      "铰链选型",
      "门厚",
      "门宽",
      "门高",
      "开门角度",
      "承重计算",
      "铰链数量",
      "参数",
      "选型参数",
      "规格选型",
      "规格参数",
      "门板重量",
      "承载能力",
      "加强型",
      "45度铰链",
    ],
  },
  {
    id: "aventos-hf",
    title: "AVENTOS HF top 大翻门上翻门",
    url: "https://publications.blum.com/2022/catalogue/zh/244/",
    summary:
      "AVENTOS HF top（大翻门上翻门）是 Blum 上翻门系列中适用于大面板和高柜的主力型号。其运动机构采用双连杆折叠机构，打开时两块面板折叠向上移动，关闭时平滑下降复位。标准开合角度为 104°（±2° 可调），可根据面板高度在 83°~108° 范围内调节。适用柜体高度范围 350~1040mm，适用面板高度 150~800mm，面板重量范围 2.0~17.5kg（由力矩决定）。选型时需计算面板力矩（力矩 = 面板重量 × 面板重心高度），对照力矩表选择 LS（低力矩）、S（中力矩）、M（高力矩）、H（超高力矩）或 HL（极高力矩）五个省力装置等级。安装时左右两只省力装置必须成对使用，且必须使用原厂连接板。HF top 可集成 BLUMOTION 阻尼实现轻柔关闭，也可选配 TIP-ON 碰碰开实现无拉手操作。",
    official: true,
    keywords: [
      "aventos hf",
      "aventos hf top",
      "大翻门",
      "双连杆",
      "上翻门",
      "吊柜",
      "高柜",
      "省力装置",
      "力矩",
      "力矩计算",
      "ls",
      "s",
      "m",
      "h",
      "hl",
      "面板高度",
      "柜体高度",
      "blumotion",
      "爱翻",],
  },
  {
    id: "aventos-hs",
    title: "AVENTOS HS top 斜移上翻门",
    url: "https://publications.blum.com/2022/catalogue/zh/244/",
    summary:
      "AVENTOS HS top（斜移上翻门）专为吊柜上方空间受限的场景设计，如安装在微波炉或抽油烟机上方的浅柜。HS 的运动机构为单杆斜移机构，门板沿对角线方向向上斜移打开，完全避开了安装空间上方的障碍物。标准开合角度为 104°（可调范围 83°~108°），适用柜体高度 300~600mm，适用面板高度 150~560mm，面板重量范围 1.5~14.0kg。省力装置同样分为 LS、S、M、H 四个等级，选型依据力矩计算结果确定。HS top 可内置 BLUMOTION 阻尼，也支持与 TIP-ON 碰碰开组合使用。由于门板斜移轨迹，需确保柜体上方预留至少 40mm 的自由空间以防碰撞。安装时需使用专用斜移连接板和限位器，保证门板运动轨迹精确。",
    official: true,
    keywords: [
      "aventos hs",
      "aventos hs top",
      "斜移上翻门",
      "浅柜",
      "斜移",
      "单杆",
      "对角线",
      "省力装置",
      "力矩",
      "blumotion",
      "tip-on",
      "吊柜",
      "斜移轨迹",
      "上方空间",
      "限位器",
      "爱翻",],
  },
  {
    id: "aventos-hl",
    title: "AVENTOS HL top 平移上翻门",
    url: "https://publications.blum.com/2022/catalogue/zh/248/",
    summary:
      "AVENTOS HL top（平移上翻门）专为高柜设计，门板沿水平方向向上平移打开，折叠收纳于柜体顶部，不占用柜体前方的操作空间。标准开合角度为 107°，可调范围 85°~110°。适用柜体高度范围 300~1220mm，是 AVENTOS 系列中适用柜高最广的型号。适用面板高度 150~800mm，面板重量范围 1.8~20.0kg。省力装置分为 S、M、H 三个等级（LS 不适用于 HL），高柜应用时需特别注意面板重心位置以确保力矩计算准确。HL top 支持 BLUMOTION 阻尼集成，也支持 TIP-ON 碰碰开。该型号由于门板平移路径的特点，特别适合配合宽大面板使用，可实现优雅的整幅面板向上翻开效果，常用于高柜和餐边柜。",
    official: true,
    keywords: [
      "aventos hl",
      "aventos hl top",
      "平移上翻门",
      "高柜",
      "水平",
      "平移",
      "省力装置",
      "力矩",
      "blumotion",
      "tip-on",
      "高柜门",
      "面板",
      "107度",
      "折叠收纳",
      "餐边柜",
      "爱翻",],
  },
  {
    id: "aventos-hk",
    title: "AVENTOS HK top / HK-S / HK-XS 上翻铰链",
    url: "https://publications.blum.com/2022/catalogue/zh/252/",
    summary:
      "AVENTOS HK top 是 AVENTOS 系列中定位为紧凑型上翻铰链的产品，以铰链结构实现面板的上翻开启，无需独立省力装置。HK top 标准开合角度 84°（可调 60°~105°），适用柜体高度 150~800mm，面板高度 100~600mm，面板重量 2.0~13.5kg，提供 LS（低力）、S（中力）、VS（高力）三种力矩版本。HK-S 相比 HK top 结构更紧凑，标准开合角度 78°（可调 55°~100°），适用柜体高度 150~600mm。HK-XS 为极致紧凑设计，标准开合角度 75°（可调 50°~95°），适用柜体高度 100~400mm 的小型柜。三个型号的共同特点是安装深度小（HK top 底座深度 38mm，HK-S 为 34mm，HK-XS 为 32mm），适合吊柜下层或浅型柜体。均支持 BLUMOTION 阻尼和 TIP-ON 碰碰开。",
    official: true,
    keywords: [
      "aventos hk",
      "aventos hk-s",
      "aventos hk-xs",
      "上翻铰链",
      "紧凑型",
      "小柜",
      "微型柜",
      "省力",
      "力矩",
      "ls",
      "vs",
      "blumotion",
      "tip-on",
      "小角度",
      "吊柜",
      "浅柜",
      "爱翻",],
  },
  {
    id: "aventos-hki",
    title: "AVENTOS HKi 内置上翻门",
    url: "https://publications.blum.com/2022/catalogue/zh/256/",
    summary:
      "AVENTOS HKi 是 AVENTOS 系列中唯一将上翻机构完全内置于柜体的型号，外部只可见优雅的开门缝隙，呈现极简的视觉效果，特别适合高端定制家具和隐形门应用。HKi 通过专用连接件将面板与柜体内部的上翻机构相连，开合角度范围 75°~105°（可调）。适用面板宽度 300~1800mm，面板高度 100~500mm，面板重量最高 10.0kg。省力装置通过计算面板力矩从 LS、S、M 中选择。该型号的安装精度要求最高，需要精确的钻孔和连接板定位，建议使用 BXF 数据格式从产品配置器直接导入 CNC 加工参数。HKi 同样支持 BLUMOTION 和 TIP-ON BLUMOTION 功能。由于外观极简，常用于展示柜、书柜和高端橱柜的开放格区域。",
    official: true,
    keywords: [
      "aventos hki",
      "内置上翻门",
      "隐形门",
      "极简",
      "隐藏",
      "简约设计",
      "高端定制",
      "省力装置",
      "力矩",
      "bxf",
      "cnc",
      "钻孔",
      "连接件",
      "blumotion",
      "展示柜",
      "爱翻",],
  },
  {
    id: "aventos-torque-selection",
    title: "AVENTOS 力矩计算与选型指南",
    url: "https://publications.blum.com/2022/catalogue/zh/260/",
    summary:
      "AVENTOS 省力装置选型的核心是力矩（Torque）计算，公式为：力矩(Nm) = 面板重量(kg) × 重力加速度(9.8m/s²) × 面板重心高度(m)。其中面板重心高度通常取面板高度的 50%（均质面板）。计算结果对照省力装置力矩表选择最接近且偏大的等级。实际选型中还需考虑：使用 BLUMOTION 阻尼时力矩需增加约 10%（阻尼机构自身阻力）；使用 TIP-ON 碰碰开时需额外增加 5%（触发机构阻力）；双门配置（HF）时每个省力装置承受的面板重量需按单侧面板计算。Blum 官方提供基于 Excel 和 Web 的力矩计算器，可从 product-configurator 或 Blum 官网下载。选型错误会导致门板开启无力或关闭速度异常，需通过 EASY ASSEMBLY 验证当前配置是否匹配。常见力矩等级参考值：LS ≈ 4~6Nm，S ≈ 6~10Nm，M ≈ 10~18Nm，H ≈ 18~30Nm，HL ≈ 30~50Nm。",
    official: true,
    keywords: [
      "力矩计算",
      "省力装置选型",
      "aventos选型",
      "力矩公式",
      "面板重量",
      "重心高度",
      "ls",
      "s",
      "m",
      "h",
      "hl",
      "nm",
      "计算器",
      "选型表",
      "力矩表",
      "参数表",
      "爱翻",],
  },
  {
    id: "legrabox",
    title: "LEGRABOX 乐薄金属抽屉系列",
    url: "https://publications.blum.com/2022/catalogue/zh/300/",
    summary:
      "LEGRABOX 乐薄是 Blum 高端抽屉系列的代表产品，以超薄侧板（仅 12.8mm 厚度）著称，视觉上极为轻盈简洁。LEGRABOX 提供四种标准侧板高度：N（低型，69mm）、M（中低型，89mm）、K（中高型，122mm）、C（高型，169mm）和 MK（特高中型，69mm）、Z MK（特高加厚型，89mm）。标称长度覆盖 270mm、300mm、350mm、400mm、450mm、500mm、550mm、600mm、650mm 共 9 个尺寸，深度适配从 320mm 到 720mm 的柜体深度。标准承重 40kg（动态），加强型（带增配重模块）可达 70kg。颜色选项包括标准灰（RAL 7037）、碳黑（RAL 9005）和白色（RAL 9016），以及不锈钢效果（inox）饰面。LEGRABOX 可搭配 MOVENTO 导轨实现 BLUMOTION 阻尼全集成，支持 TIP-ON 碰碰开无拉手设计，也可搭配 AMBIA-LINE 内分隔系统。",
    official: true,
    keywords: [
      "legrabox",
      "乐薄",
      "金属抽屉",
      "超薄",
      "高端抽屉",
      "12.8mm",
      "侧板高度",
      "nk",
      "mk",
      "zmk",
      "movento",
      "ambia-line",
      "40kg",
      "70kg",
      "阻尼",
      "无把手",
    ],
  },
  {
    id: "merivobox",
    title: "MERIVOBOX 魅宝金属抽屉系列",
    url: "https://publications.blum.com/2022/catalogue/zh/330/",
    summary:
      "MERIVOBOX 魅宝是 Blum 中端金属抽屉系列，以其高性价比和灵活的模块化设计著称。相比 LEGRABOX 的 12.8mm 超薄侧板，MERIVOBOX 侧板厚度为 17mm，提供更大的结构强度和更低的成本。MERIVOBOX 提供 5 种侧板高度：50N（50mm）、N（68mm）、M（101mm）、K（144mm）、B（233mm），标称长度从 270mm 到 650mm，适配柜体深度 300~720mm。标准承重为 30kg，加强型可达 50kg。该系列采用 Z35E 导轨（内置 BLUMOTION 阻尼）和 Z35AI 导轨（带 TIP-ON 碰碰开）的双轨系统。标准套装（Z38F/Z40H 系列）包含抽屉侧板、导轨、后面板、底板连接件和装饰盖板，颜色为白色（RAL 9016）和灰色（RAL 7037）。",
    official: true,
    keywords: [
      "merivobox",
      "魅宝",
      "金属抽屉",
      "中端",
      "性价比",
      "模块化",
      "17mm",
      "侧板高度",
      "z35e",
      "z35ai",
      "30kg",
      "50kg",
      "套装",
      "ambia-line",
      "blumotion",
      "tip-on",
    ],
  },
  {
    id: "tandembox",
    title: "TANDEMBOX 豪华金属抽屉系列",
    url: "https://publications.blum.com/2022/catalogue/zh/350/",
    summary:
      "TANDEMBOX 豪华金属抽屉是 Blum 抽屉系列中的经典产品，采用更厚实的侧板设计（27mm 厚度），强调结构稳固和耐用性。TANDEMBOX 提供 4 种侧板高度：I（54mm 内抽）、K（83mm 中抽）、K+（112mm 抽屉）、B（235mm 高抽），标称长度覆盖 260mm 到 650mm。标准承重 30kg，可选配增配重模块提升至 50kg。该系列最大特点是与 TANDEM 导轨系统深度整合，导轨隐藏在侧板内部，支持 3/4 拉出（标准型）或全拉出（BLUMOTION 型）。TANDEMBOX 可集成 BLUMOTION 阻尼（内置于导轨中）和 TIP-ON 碰碰开（通过 Z10I 适配器），并支持 ORGA-LINE 金属丝内分隔系统。颜色选项包括白色（RAL 9016）和灰色（RAL 7037），侧面可见金属本色装饰条是该系列的标志性设计元素。",
    official: true,
    keywords: [
      "tandembox",
      "豪华金属抽",
      "经典抽屉",
      "27mm",
      "侧板厚度",
      "tandem",
      "orgaline",
      "30kg",
      "50kg",
      "blumotion",
      "tip-on",
      "全拉出",
      "3/4拉出",
      "内分隔",
      "金属丝分隔",
    ],
  },
  {
    id: "tandembox-drawer-sides",
    title: "TANDEMBOX drawer sides 豪华金属抽侧帮单独订购",
    url: "https://publications.blum.com/2022/catalogue/zh/352/",
    summary:
      "TANDEMBOX drawer sides 是指 TANDEMBOX 抽屉系统中侧帮（抽屉侧板）可单独订购的配件选项，主要用于替换损坏的侧板或按项目需求单独采购。侧帮高度分为 I（54mm）、K（83mm）、K+（112mm）、B（235mm）四种，对应不同的抽屉高度需求。每根侧帮的长度规格与 TANDEMBOX 标称长度一致（270mm~650mm），材质为冷轧镀锌钢板，表面可做喷粉（RAL 9016 白色、RAL 7037 灰色）或电泳处理。单独订购时侧帮编号格式为 T51XXXZ（具体编号见订购手册），常与导轨、后面板、底板连接件等配件分开订购以便灵活配置。需要注意的是，侧帮与导轨的型号必须严格匹配（BLUMOTION 型侧帮开有阻尼槽，标准型侧帮无此槽），混用将导致功能异常。",
    official: true,
    keywords: [
      "tandembox",
      "侧帮",
      "侧板",
      "抽屉侧板",
      "单独订购",
      "配件",
      "替换",
      "豪华金属抽",
      "t51",
      "侧帮高度",
      "规格",
      "镀锌",
      "blumotion型",
      "标准型",
      "喷粉",
    ],
  },
  {
    id: "space-tower",
    title: "SPACE TOWER 摘云台",
    url: "https://publications.blum.com/2022/catalogue/zh/570/",
    summary:
      "SPACE TOWER 摘云台是 Blum 针对橱柜转角死角设计的高柜储物完整解决方案，利用转角空间实现逐层全拉出和三面取物。该系统由两组对称的金属抽结构组成，通过中央交叉连杆实现同步开合动作。SPACE TOWER 提供两种宽度规格：500mm（标准 L 型转角柜）和 600mm（宽型转角柜），高度可从 400mm 覆盖到 2000mm，适配不同高度的高柜。标称深度从 500mm 到 650mm 可选。每层承载能力为 25kg（动态），整体系统承重可达 100kg 以上。SPACE TOWER 采用 TANDEMBOX 侧板和 TANDEM 导轨系统（支持 BLUMOTION 阻尼全拉出），可搭配 ORGA-LINE 分隔件实现内部收纳分类。该系统安装需专用转角连接件和加固背板，柜体必须为实墙或重型加固结构以承受使用过程中的侧向力。",
    official: true,
    keywords: [
      "space tower",
      "摘云台",
      "转角柜",
      "高柜储物",
      "死角",
      "全拉出",
      "三面取物",
      "tandembox",
      "tandem",
      "orgaline",
      "转角",
      "25kg",
      "同步开合",
      "l型柜",
      "储物柜",
    ],
  },
  {
    id: "space-step",
    title: "SPACE STEP 踏步储物方案",
    url: "https://publications.blum.com/2022/catalogue/zh/580/",
    summary:
      "SPACE STEP 是 Blum 将地柜踢脚区域转化为功能性储物和踩踏平台的创新方案。该系统将传统 100~150mm 高的踢脚空间改造为带隐藏抽屉的储物单元，同时其顶面可作为踏凳使用，方便取用高柜和上层物品。SPACE STEP 承载能力：踏面静态承重 150kg，动态承重 100kg；内置抽屉承重 20kg。标准宽度规格为 600mm、800mm、900mm、1000mm 和 1200mm，深度与标准地柜深度匹配（560~650mm）。踢脚高度可调，范围 80~200mm。SPACE STEP 采用 LEGRABOX 抽屉结构（LEGRABOX N 型侧板），搭配标准 BLUMOTION 阻尼导轨，安装高度低至 67mm。该系统需与地柜门板联动开合（通过连接杆和铰链），安装时需注意地面平整度（误差需控制在 ±2mm 以内）以保证踏面水平。",
    official: true,
    keywords: [
      "space step",
      "踏步储物",
      "踢脚",
      "踢脚储物",
      "踏凳",
      "踩踏",
      "legrabox",
      "blumotion",
      "150kg",
      "地柜",
      "功能储物",
      "隐藏抽屉",
      "地面平整",
      "可调脚",
    ],
  },
  {
    id: "movento",
    title: "MOVENTO 魔顺畅隐藏式导轨",
    url: "https://publications.blum.com/2022/catalogue/zh/400/",
    summary:
      "MOVENTO 魔顺是 Blum 高端木抽导轨系统，专为木质抽屉设计，支持内置 BLUMOTION 阻尼功能。MOVENTO 提供两种负载等级：标准型（40kg 动态承重）和加强型 BLUMOTION（70kg 动态承重）。标称长度系列：270mm、300mm、320mm、350mm、380mm、400mm、420mm、450mm、480mm、500mm、520mm、550mm、580mm、600mm、650mm、700mm、750mm，共 17 个尺寸，覆盖柜体深度 300~800mm。MOVENTO 导轨内置同步机构，保证两侧导轨同步运动，偏差控制在 0.1mm 以内。导轨截面高度仅 38mm（标准型），可适配 12~19mm 厚度的木质抽屉侧板。BLUMOTION 阻尼功能通过导轨内部的油压阻尼器实现，可根据面板重量通过调节螺丝进行阻尼强度微调（1~5 档）。MOVENTO 支持 SERVO-DRIVE 电动开启适配，可与 TIP-ON 机构组合实现按压开门。",
    official: true,
    keywords: [
      "movento",
      "魔顺",
      "木抽导轨",
      "隐藏式导轨",
      "40kg",
      "70kg",
      "同步导轨",
      "blumotion",
      "阻尼",
      "阻尼调节",
      "servo-drive",
      "tip-on",
      "油压阻尼",
      "木质抽屉",
      "导轨",
    ],
  },
  {
    id: "tandem",
    title: "TANDEM 隐顺畅隐藏式导轨",
    url: "https://publications.blum.com/2022/catalogue/zh/410/",
    summary:
      "TANDEM 隐顺是 Blum 经典定位的木抽导轨系统，定位于 MOVENTO 之下，以经济实用的特点广泛用于标准木质抽屉。TANDEM 提供三种负载等级：TANDEM 标准型（30kg）、TANDEM BLUMOTION 型（40kg）和 TANDEM plus 重载型（50kg）。标称长度系列从 270mm 到 750mm，共 14 个标准尺寸，适配柜体深度 300~800mm。TANDEM 导轨高度为 35mm，适配 12~19mm 木质抽屉侧板。该导轨系统通过尼龙滚轮和钢球轴承组合实现滑动，开合手感顺畅无杂音。TANDEM BLUMOTION 型内置 BLUMOTION 阻尼，阻尼特性与 MOVENTO 相同但承重略低。TANDEM 也支持与 TIP-ON 碰碰开机构组合使用，通过 Z10I 适配件连接。该系列是橱柜厂和家具厂大批量标准配置中最为常见的导轨方案之一。",
    official: true,
    keywords: [
      "tandem",
      "隐顺",
      "木抽导轨",
      "隐藏式导轨",
      "30kg",
      "40kg",
      "50kg",
      "tandem blumotion",
      "tandem plus",
      "阻尼",
      "tip-on",
      "经济型",
      "标准配置",
      "导轨",
      "滚轮",
    ],
  },
  {
    id: "blumotion",
    title: "BLUMOTION 阻尼闭合技术详解",
    url: "https://www.blum.com.cn/cn/zh/products/motion-technologies/blumotion/overview/",
    summary:
      "BLUMOTION 是 Blum 自研的油压阻尼闭合技术，通过内置于产品内部的油压缓冲器实现轻柔、无冲击的关闭效果。其工作原理是利用硅油通过精密节流孔时的粘滞阻力，将动能转化为热能缓慢释放，从而在最后 30~50mm 的行程范围内持续减速直至完全关闭。BLUMOTION 的关键参数：适用关闭速度范围 0.3~1.5m/s，阻尼力矩可调节 1~5 档（通过旋转调节螺丝），适用温度范围 -30°C~+80°C，适用产品包括铰链（CLIP top BLUMOTION）、抽屉（内置于 MOVENTO、TANDEMBOX、LEGRABOX、MERIVOBOX 导轨）和上翻门（AVENTOS 全系列内置）。BLUMOTION 不可后加装（必须在采购时选择对应型号），但可在使用中通过调节螺丝进行微调以适应不同面板重量。阻尼失效的常见原因包括：温度极端导致硅油黏度变化（寒冷环境黏度增大，关闭变慢；高温环境黏度降低，阻尼减弱）、长期使用后硅油微量渗漏（不可维修，需更换整个阻尼单元）。",
    official: true,
    keywords: [
      "blumotion",
      "阻尼",
      "油压阻尼",
      "硅油",
      "缓冲",
      "轻柔关闭",
      "阻尼调节",
      "阻尼力矩",
      "温度",
      "关闭速度",
      "无冲击",
      "动感技术",
      "blumotion调节",
      "阻尼失效",
      "保养",
    ],
  },
  {
    id: "tip-on",
    title: "TIP-ON 碰碰开按压开门系统",
    url: "https://www.blum.com.cn/cn/zh/products/motion-technologies/tip-on/overview/",
    summary:
      "TIP-ON 是 Blum 的按压式无拉手开门技术，通过按压柜门面板触发内部弹簧机构实现门板弹出。其核心组件包括触发器（Trigger）和弹出器（Pusher）两部分：触发器安装于门板内侧，按压门面时触发；弹出器安装于柜体侧板，将门板从关闭位置推出 10~35mm。TIP-ON 的技术参数：触发压力 7~10N（约 700~1000gf），适用门重 8~40kg，弹出距离 10~35mm（可调），适用面板厚度 15~32mm，触发灵敏度可调节范围 1~6mm（通过旋转触发器上的调节螺丝，数字越大越灵敏）。该系统可用于三种应用：柜门（需配合 CLIP top 或 MODUL 铰链）、抽屉（配合 MOVENTO、TANDEMBOX、LEGRABOX）和上翻门（配合 AVENTOS 系列）。注意事项：TIP-ON 不适用于门板重量超过 40kg 的场景（触发力不足），也不适用于冷压板或低密度刨花板（板面刚性不足导致触发不灵敏）。",
    official: true,
    keywords: [
      "tip-on",
      "碰碰开",
      "按压开门",
      "push-to-open",
      "无拉手",
      "免把手",
      "触发压力",
      "弹出器",
      "触发器",
      "灵敏度",
      "调节",
      "无把手设计",
      "柜门开启",
      "抽屉开启",
      "碰触开门",
    ],
  },
  {
    id: "tip-on-blumotion",
    title: "TIP-ON BLUMOTION 阻尼碰碰开二合一系统",
    url: "https://www.blum.com.cn/cn/zh/products/motion-technologies/tip-on-blumotion/overview/",
    summary:
      "TIP-ON BLUMOTION 是 Blum 将 TIP-ON 碰碰开与 BLUMOTION 阻尼闭合功能集于一体的二合一解决方案，通过一次安装同时实现按压开门和轻柔关闭两种功能。核心优势在于减少安装步骤和配件数量，降低采购和安装成本。该系统的工作原理：开门时按压面板触发 TIP-ON 弹出机构，门板弹开后由铰链或导轨完成开启动作；关闭时 BLUMOTION 阻尼机构介入，在最后阶段持续减速直至轻柔关闭。TIP-ON BLUMOTION 的技术参数：触发压力 7~10N，适用面板重量 10~35kg，弹出距离 10~30mm，阻尼特性与独立 BLUMOTION 相同（可调 1~5 档）。目前支持 CLIP top BLUMOTION 铰链（配合 TIP-ON for doors）、LEGRABOX/MERIVOBOX 抽屉（配合内置式 TIP-ON）和 TANDEMBOX 抽屉（配合 Z10I 适配器）。安装时需注意门板与柜体侧板间隙 ≥ 2mm，面板厚度 ≥ 16mm。",
    official: true,
    keywords: [
      "tip-on blumotion",
      "阻尼碰碰开",
      "二合一",
      "一体式",
      "碰碰开",
      "阻尼",
      "按压开门",
      "轻柔关闭",
      "无拉手",
      "clip top blumotion",
      "legrabox",
      "merivobox",
      "tandembox",
      "集成",
      "组合功能",
    ],
  },
  {
    id: "servo-drive",
    title: "SERVO-DRIVE 电动开启系统",
    url: "https://www.blum.com.cn/cn/zh/products/motion-technologies/servo-drive/overview/",
    summary:
      "SERVO-DRIVE 是 Blum 的电动辅助开启系统，通过电机驱动实现柜门和抽屉的自动开启，适用于行动不便的老年人用户或有高品质生活需求的场景。系统工作电压 24V DC（安全特低电压），功耗 5W（待机功耗 < 0.5W），适配 Blum 变压器（输入 220V AC/50Hz，输出 24V DC，最大负载 60W）。开启方式支持三种：轻触开门（轻触面板任意位置触发）、近场感应（手靠近面板约 50mm 时自动开门）和 APP 遥控（通过蓝牙连接手机 APP 控制）。SERVO-DRIVE 可与 CLIP top BLUMOTION 铰链、MOVENTO 导轨、TANDEMBOX、LEGRABOX、AVENTOS 全系列组合使用。与 TIP-ON 的主要区别：SERVO-DRIVE 是主动驱动开启（电机推动），而 TIP-ON 是被动弹出（弹簧释放），因此 SERVO-DRIVE 适合更重的面板（可达 50kg）。系统包含控制单元、驱动电机、连接线和传感器，安装需预留电源和走线空间。",
    official: true,
    keywords: [
      "servo-drive",
      "电动开启",
      "电机驱动",
      "自动开门",
      "24v",
      "无障碍",
      "老年人",
      "app控制",
      "蓝牙",
      "轻触开门",
      "近场感应",
      "变压器",
      "电动",
      "自动",
      "智能",
    ],
  },
  {
    id: "servo-drive-flex",
    title: "SERVO-DRIVE flex 灵活可选开系统",
    url: "https://www.blum.com.cn/cn/zh/products/motion-technologies/servo-drive/overview/",
    summary:
      "SERVO-DRIVE flex 是 SERVO-DRIVE 电动开启系统的灵活版本，增加了可选开（selective opening）功能，用户可以选择性地只打开某一个柜门或抽屉，而非全部同时打开。在标准 SERVO-DRIVE 配置中，接近感应触发时同一组的所有柜门/抽屉会同时开启；而 SERVO-DRIVE flex 通过在每个触发点增加独立的红外传感器，实现独立感应和选择性触发。该系统特别适合安装在高柜组合中（如衣柜多门柜），用户可以走近并触碰想要打开的那扇门，而不会影响其他已关闭的门。SERVO-DRIVE flex 的技术规格与标准 SERVO-DRIVE 一致（24V DC，5W），但控制单元容量更大（支持最多 6 个独立通道 vs 标准版的 3 个通道）。安装时每个感应点需要独立布线和校准，支持与 BLUMOTION 和 TIP-ON 全系列组合。",
    official: true,
    keywords: [
      "servo-drive flex",
      "可选开",
      "选择性开门",
      "电动开启",
      "独立感应",
      "红外感应",
      "多通道",
      "衣柜",
      "高柜",
      "无障碍",
      "灵活",
      "6通道",
      "SERVO",
      "电机驱动",
    ],
  },
  {
    id: "revego-single",
    title: "REVEGO 单门口袋门系统",
    url: "https://publications.blum.com/2022/catalogue/zh/600/",
    summary:
      "REVEGO 单门是 Blum 口袋门系列中用于单扇门隐藏式应用的解决方案，当门板打开时通过侧向滑入柜体两侧的固定板之间，整个柜体正面呈现开放状态。REVEGO 单门系统适用面板宽度 300~1200mm，面板高度 300~2400mm，面板重量最高 25kg。安装要求：柜体最小深度（安装净空）为 200mm（单门），面板厚度范围 16~28mm，固定板（pocket profile）标准材质为铝合金，表面处理有银色和深灰两色可选。铰链类型为 35mm 罩杯 CLIP top（0 盖或 1 盖），开门角度 108°（可调 90°~120°）。轨道系统采用低摩擦滑轨和内置弹簧平衡机构，保证门板运动轻盈平稳。该系统支持与 BLUMOTION 阻尼闭合集成（通过 BLUMOTION 铰链），也可选配 TIP-ON 碰碰开实现无拉手设计。规划时需特别注意左右两侧固定板与门板之间的间隙预留（每侧 ≥ 5mm），以及门板关闭时的磁吸定位装置位置。",
    official: true,
    keywords: [
      "revego",
      "单门",
      "口袋门",
      "隐藏门",
      "单扇门",
      "侧滑",
      "固定板",
      "面板宽度",
      "铝合金",
      "弹簧平衡",
      "磁吸",
      "blumotion",
      "tip-on",
      "无拉手",
      "25kg",
    ],
  },
  {
    id: "revego-dual",
    title: "REVEGO 双门口袋门系统",
    url: "https://publications.blum.com/2022/catalogue/zh/602/",
    summary:
      "REVEGO 双门是用于双扇门同步隐藏式应用的解决方案，两扇门板可同时向两侧滑开，露出完整的柜体开口，适用于衣柜、书柜或展示柜等需要大面积开放的应用场景。REVEGO 双门系统适用面板总宽度 600~2400mm（每扇 300~1200mm），面板高度 300~2400mm，每扇面板重量最高 25kg。安装要求：柜体最小深度（安装净空）为 225mm（双门），面板厚度范围 16~28mm。固定板系统为双侧铝合金导轨，每侧可容纳一扇门板滑入。两扇门板通过同步连杆机构实现同时开合动作，保证运动同步性。开门角度 108°（可调 90°~120°）。该系统同样支持 BLUMOTION 阻尼闭合和 TIP-ON 碰碰开。规划时需预留中间分离缝（4~6mm）和两侧安全间隙，且双门系统的柜体必须为实墙结构以承受侧向力。",
    official: true,
    keywords: [
      "revego",
      "双门",
      "口袋门",
      "隐藏门",
      "双扇门",
      "同步",
      "连杆",
      "固定板",
      "双侧",
      "衣柜",
      "书柜",
      "展示柜",
      "blumotion",
      "tip-on",
      "225mm",
    ],
  },
  {
    id: "revego-planning",
    title: "REVEGO 规划与加工指南",
    url: "https://publications.blum.com/2022/catalogue/zh/604/",
    summary:
      "REVEGO 口袋门系统的精确规划必须通过 Blum 产品配置器或官方规划手册进行，因为涉及多个关键尺寸参数：柜体总深度（含固定板）：单门 ≥ 230mm，双门 ≥ 255mm；门板宽度 = 柜体净开口宽度 + 重叠量（单门重叠量 40mm，双门每侧重叠量 20mm）；门板高度需考虑门板上下间隙（各 3mm）；固定板安装槽深度 15mm，宽度 38mm；门板安装孔位必须与 CLIP top 35mm 罩杯铰链参数精确匹配。加工要求：固定板安装槽需 CNC 铣槽（精度 ±0.3mm），滑轨安装面需铣平（平面度 0.1mm/1000mm），门板钻孔必须使用 Blum 专用钻头（直径 35mm + 8mm 定位孔）。所有规划数据可通过 BXF 格式从产品配置器导出，直接对接 CNC 加工设备。REVEGO 规划还需考虑地面不平导致的门板歪斜问题，建议柜体底部增加可调脚。",
    official: true,
    keywords: [
      "revego规划",
      "口袋门加工",
      "bxf",
      "cnc加工",
      "固定板",
      "滑轨",
      "门板宽度",
      "门板高度",
      "重叠量",
      "安装槽",
      "规划参数",
      "钻孔",
      "配置器",
      "铣槽",
      "地板不平",
    ],
  },
  {
    id: "ambia-line",
    title: "AMBIA-LINE 内分隔系统（LEGRABOX/MERIVOBOX）",
    url: "https://publications.blum.com/2022/catalogue/zh/500/",
    summary:
      "AMBIA-LINE 是 Blum 专为 LEGRABOX 乐薄和 MERIVOBOX 魅宝抽屉设计的内部分隔系统，通过在抽屉底部预埋的导轨槽中嵌入各种分隔组件，实现抽屉内部空间的多功能分区。AMBIA-LINE 的分隔组件包括：纵向分隔板（高度 54mm，宽度可调 50~200mm）、横向分隔板（高度 35mm，用于分层）、刀叉盘（高度 25mm，带凹槽固定餐具）、瓶架（高度 80mm，用于酒瓶和大件调味品）、药盒托（高度 50mm，带防滑硅胶垫）。适用抽屉宽度范围 300~1200mm，组件颜色统一为碳灰色（RAL 9005）。安装方式：分隔板通过磁铁或卡扣固定在抽屉底部的预置导轨槽中，无需任何工具即可自由拆装和重新组合。AMBIA-LINE 所有组件均采用食品级 ABS 材料，可与洗碗机配件（需拆卸）配合使用，适用于厨房、浴室和办公家具等多种场景。",
    official: true,
    keywords: [
      "ambia-line",
      "乐比翼",
      "内分隔",
      "分隔系统",
      "legrabox",
      "merivobox",
      "刀叉盘",
      "瓶架",
      "收纳",
      "分区",
      "磁铁",
      "卡扣",
      "厨房收纳",
      "抽屉分隔",
      "abs材料",
    ],
  },
  {
    id: "orga-line",
    title: "ORGA-LINE 内分隔系统（TANDEMBOX）",
    url: "https://publications.blum.com/2022/catalogue/zh/510/",
    summary:
      "ORGA-LINE 是 Blum 专为 TANDEMBOX 豪华金属抽屉设计的金属丝内分隔系统，通过在抽屉侧面预装的导向块中插入各种金属丝组件，实现 TANDEMBOX 抽屉内部的有序收纳。ORGA-LINE 组件体系包含：金属丝纵向分隔板（高度 41mm 和 80mm 两种）、横向分隔板（高度 30mm）、刀叉盘（标准型和加高型）、瓶架、调味品架和定制宽度分隔件。所有组件材质为电镀钢丝（直径 3mm），表面做镀镍处理，防锈耐用。适用抽屉宽度范围 300~1200mm，颜色统一为银镍色。ORGA-LINE 与 TANDEMBOX 的安装接口为抽屉侧板背面的预制卡槽（Blum 称之为\"导向块\"），分隔板直接插入卡槽并通过弹性卡扣固定。与 AMBIA-LINE 的主要区别在于：ORGA-LINE 采用金属丝而非实心塑料，更通透便于观察内部物品，但防泼溅能力略弱。",
    official: true,
    keywords: [
      "orga-line",
      "内分隔",
      "金属丝分隔",
      "tandembox",
      "豪华金属抽",
      "钢丝",
      "刀叉盘",
      "瓶架",
      "调味品架",
      "收纳",
      "分区",
      "卡槽",
      "电镀",
      "防锈",
      "金属丝",
    ],
  },
  {
    id: "organization-guide",
    title: "Blum 内分隔系统选型指南",
    url: "https://publications.blum.com/2022/catalogue/zh/520/",
    summary:
      "Blum 内分隔系统选型需要综合考虑抽屉系列、柜体宽度、收纳用途和个人偏好四个维度。抽屉系列对应：LEGRABOX 和 MERIVOBOX 优先选择 AMBIA-LINE（实心塑料，防水性好，承载能力更强）；TANDEMBOX 优先选择 ORGA-LINE（金属丝，通透美观，与 TANDEMBOX 风格一致）；TANDEM 木抽可使用通用型分隔件但无专用系统。柜体宽度：窄柜（300~500mm）建议仅使用纵向分隔（1~2 个分区）；标准柜（500~800mm）建议纵向 + 横向组合；宽柜（800~1200mm）建议多分区布局并配合专项功能件（刀叉盘、瓶架）。收纳用途：厨房首选刀叉盘 + 调味品架 + 纵向分区；浴室首选防水分隔板 + 药盒托；办公抽屉首选文件分隔板 + 笔筒托。个人偏好：偏好整洁隐藏选 AMBIA-LINE，偏好一目了然选 ORGA-LINE。",
    official: true,
    keywords: [
      "内分隔选型",
      "选型指南",
      "ambia-line",
      "orga-line",
      "legrabox",
      "merivobox",
      "tandembox",
      "抽屉分隔",
      "收纳设计",
      "厨房收纳",
      "分区布局",
      "刀叉盘",
      "瓶架",
      "功能件",
      "收纳整理",
    ],
  },
  {
    id: "minipress-m",
    title: "MINIPRESS M 数控钻孔设备",
    url: "https://publications.blum.com/2022/catalogue/zh/700/",
    summary:
      "MINIPRESS M 是 Blum 推出的数控钻孔机，用于在柜体侧板、门板和抽屉部件上精确钻出 Blum 五金件（铰链、导轨、上翻门等）的安装孔位。MINIPRESS M 采用三轴数控结构，钻孔精度 ±0.1mm，可编程存储 99 组钻孔程序。适配钻头规格：35mm 罩杯钻头（用于铰链）、8mm 定位钻（用于导轨连接件）、5mm 木螺丝导孔钻。加工范围：X 轴（宽度）50~2400mm，Y 轴（深度）50~800mm，Z 轴（厚度）8~60mm。MINIPRESS M 支持通过 USB 或以太网接口导入 BXF 数据文件，自动读取五金件钻孔参数并执行加工，无需手动编程。设备标配激光定位系统和数字显示屏，支持手动微调。安全功能包括紧急停止开关、过载保护和钻头冷却液自动供给系统。适用场景：橱柜厂、家具厂和定制家具加工中心。",
    official: true,
    keywords: [
      "minipress m",
      "钻孔机",
      "数控钻孔",
      "cnc",
      "bxf",
      "钻孔精度",
      "35mm钻头",
      "铰链钻孔",
      "导轨钻孔",
      "加工设备",
      "usb",
      "以太网",
      "激光定位",
      "橱柜加工",
      "数控机床",
    ],
  },
  {
    id: "minipress-p",
    title: "MINIPRESS P 压装设备",
    url: "https://publications.blum.com/2022/catalogue/zh/702/",
    summary:
      "MINIPRESS P 是 Blum 的电动压装设备，用于将 Blum 五金件（导轨连接器、抽屉后面板卡扣、铰链底座等）压入预先钻好的安装孔中，实现快速可靠的机械连接。MINIPRESS P 的压装力调节范围 500~5000N，可适配从小型连接件到重型导轨的各种规格。压装行程 80mm，压装速度可调（3~15mm/s）。设备配备数字压力传感器，实时显示实际压装力，当压力偏离设定值超过 15% 时自动停止并报警（防止工件未压到位或压装过深）。MINIPRESS P 支持与 MINIPRESS M 通过蓝牙联动，形成钻孔-压装一体化工作站。设备自带 6 种标准压装模具（适配 Blum 全系列连接件），专用模具可按需额外订购。适用场景：大批量标准化生产的橱柜厂和家具厂。",
    official: true,
    keywords: [
      "minipress p",
      "压装设备",
      "压装",
      "连接件",
      "导轨",
      "抽屉",
      "压装力",
      "蓝牙",
      "一体化",
      "钻孔",
      "加工设备",
      "模具",
      "压力传感器",
      "自动化",
      "5000n",
    ],
  },
  {
    id: "easystick",
    title: "EASYSTICK 数控钻孔定位系统",
    url: "https://publications.blum.com/2022/catalogue/zh/710/",
    summary:
      "EASYSTICK 是 Blum 的数字化钻孔定位辅助工具，通过激光投影和蓝牙通信将钻孔位置信息实时投射到工件表面，引导操作人员精确钻孔。EASYSTICK 系统由三部分组成：EASYSTICK 软件（运行于 PC 或平板，用于计算钻孔坐标）、EASYSTICK 投影仪（固定于钻床上方，投射激光十字线）和 EASYSTICK 适配器（连接投影仪与钻床，接收坐标数据并驱动投影仪）。投影精度 ±0.3mm，最大工作范围 2000mm × 800mm。软件支持手动输入坐标或直接导入 BXF 文件自动解析。EASYSTICK 可与主流品牌的手电钻和台钻配合使用（通过标准夹头适配器），无需购买专用钻孔设备即可实现数字化钻孔定位。适用场景：中小型定制家具厂和改装现有设备。",
    official: true,
    keywords: [
      "easystick",
      "钻孔定位",
      "激光投影",
      "蓝牙",
      "bxf",
      "数控",
      "坐标",
      "激光十字线",
      "投影仪",
      "定位系统",
      "数字化",
      "改装",
      "台钻",
      "手持钻",
      "投影精度",
    ],
  },
  {
    id: "easystick-300",
    title: "EASYSTICK 300 多点位并行钻孔系统",
    url: "https://publications.blum.com/2022/catalogue/zh/712/",
    summary:
      "EASYSTICK 300 是 EASYSTICK 系列的升级版本，专为需要同时在多个点位钻孔的场景设计，支持一台投影仪连接最多 3 个独立的钻孔点位，实现多人并行作业大幅提升效率。EASYSTICK 300 的投影亮度提升至 12000 流明（在车间照明环境下清晰可见），工作范围扩展至 3000mm × 1000mm，支持更大幅面的工件。软件端增加了工序管理功能，可将多个钻孔程序串联为连续工序，自动切换投影位置和程序编号。EASYSTICK 300 增加了 CAD 接口，可直接导入 DXF 格式的工件轮廓图并自动识别钻孔位置。与 BXF 格式完全兼容，可从 Blum 产品配置器直接导出加工数据。适用场景：大型橱柜厂、多工位家具加工中心和需要高吞吐量的批量生产环境。",
    official: true,
    keywords: [
      "easystick 300",
      "多工位",
      "并行钻孔",
      "12000流明",
      "bxf",
      "dxf",
      "cad",
      "工序管理",
      "投影亮度",
      "大幅面",
      "批量生产",
      "数控",
      "激光投影",
      "多人作业",
      "吞吐",
    ],
  },
  {
    id: "bxf-format",
    title: "BXF 数据交换格式",
    url: "https://www.blum.com/us/en/services/e-services/onlineproductconfigurator/",
    summary:
      "BXF（Blum eXchange Format）是 Blum 专有的产品数据交换格式，用于在 Blum 配置器与 CAD/CAM 系统、加工设备之间传递五金件规划、裁切和钻孔信息。BXF 文件为 XML 格式，包含以下核心数据模块：五金件清单（部件编号、数量、位置坐标）、钻孔指令（孔径、孔深、孔位 X/Y/Z 坐标、是否通孔）、裁切指令（切割线起点终点、切割深度、锯片宽度补偿）和装配顺序（建议的五金安装步骤）。BXF 可从 Blum 产品配置器导出（选配 BXF 输出格式），也可被主流木工 CAM 软件（如 Homag iX、iCad 等）直接读取。MINIPRESS M 和 EASYSTICK 系列均可直接解析 BXF 文件执行自动化加工。BXF 的优势在于数据格式开放、字段定义规范，避免了手动输入导致的规划错误和加工失误。",
    official: true,
    keywords: [
      "bxf",
      "数据格式",
      "xml",
      "blum exchange format",
      "产品数据",
      "钻孔数据",
      "裁切数据",
      "cam",
      "cad",
      "配置器",
      "数据交换",
      "加工数据",
      "自动化",
      "homag",
      "ix",
    ],
  },
  {
    id: "easy-assembly",
    title: "EASY ASSEMBLY 线上安装助手",
    url: "https://www.blum.com/us/en/services/e-services/easyassemblyapp/",
    summary:
      "EASY ASSEMBLY 是 Blum 提供的免费在线安装辅助平台，收录了 Blum 全系列产品的安装说明、调节教程视频、常见问题排查指南和配件选购建议。内容按产品系列分类组织（铰链、上翻门、抽屉、导轨、动感技术等），支持关键词搜索和 PDF 下载（支持离线使用）。每个产品的 EASY ASSEMBLY 页面包含：产品概述（规格参数）、安装步骤详解（含高清图示和视频）、三维调节教程（高度/左右/深度的调节螺丝位置和旋转方向）、故障排查（按症状分类：异响、阻尼失效、门缝不均、弹开无力等）以及相关配件推荐。视频内容提供中文配音，并标注每个步骤的关键提示（\"注意：此时请使用力矩螺丝刀\"等）。EASY ASSEMBLY 还提供安装时间参考和所需工具清单，帮助安装人员提前准备。",
    official: true,
    keywords: [
      "easy assembly",
      "安装助手",
      "安装教程",
      "视频",
      "调节",
      "排障",
      "排查",
      "故障",
      "异响",
      "阻尼",
      "调节螺丝",
      "安装说明",
      "pdf下载",
      "中文",
      "离线",
    ],
  },
  {
    id: "product-configurator",
    title: "Blum 产品配置器",
    url: "https://www.blum.com/us/en/services/e-services/onlineproductconfigurator/",
    summary:
      "Blum 产品配置器是在线选型工具，可根据用户输入的应用参数（柜体尺寸、面板重量、门板数量、所需功能等）自动筛选并推荐最合适的 Blum 五金件组合，输出经过技术校验的完整物料清单（BOM）和 CAD/CAM 数据。配置器支持三种输入模式：向导式（逐步引导输入参数，适合新手）、参数式（直接输入规格数字，适合有经验用户）和批量式（通过 CSV 导入多组参数，适合橱柜厂批量规划）。输出内容包括：产品编号清单（精确到每个配件）、五金件布局坐标图、2D/3D CAD 模型（STEP、IGES、DXF 格式）、钻孔加工图和 BXF 数据文件。配置结果可一键发送给 Blum 授权经销商进行报价和订购。产品配置器还提供选型冲突检测（当输入参数超出产品承受范围时自动警告）和替代方案推荐（当首选产品缺货时推荐等效替代品）。",
    official: true,
    keywords: [
      "配置器",
      "product configurator",
      "选型",
      "bom",
      "物料清单",
      "零件清单",
      "cad",
      "cam",
      "bxf",
      "step",
      "iges",
      "dxf",
      "向导式",
      "批量式",
      "csv",
    ],
  },
  {
    id: "product-data",
    title: "Blum 产品数据库与 CAD/CAM 下载服务",
    url: "https://www.blum.com/us/en/services/e-services/productdatabase/",
    summary:
      "Blum 产品数据库是官方产品技术数据集中平台，提供 Blum 全系列产品的技术规格表、产品尺寸图、规划指南、安装说明和 CAD 模型下载。用户可通过产品编号或产品系列名称检索所需数据。每个产品的数据页面包含：三维尺寸图（标注关键尺寸和调节范围）、承重参数表、开合角度范围、材料与表面处理选项、可选配件列表和适用标准认证信息。CAD 模型覆盖主流格式，包括 3D：STEP（通用）、IGES（通用）、SolidWorks（.sldprt）、Revit（.rfa）；2D：DWG、DXF、PDF 工程图。数据更新频率与新产品发布同步，所有数据均提供中文版本。产品数据库还提供软件插件，可直接在 SketchUp、AutoCAD、SolidWorks 等设计软件中调用 Blum 产品模型（需注册 Blum 账号免费下载）。",
    official: true,
    keywords: [
      "产品数据库",
      "product database",
      "cad",
      "cam",
      "3d模型",
      "step",
      "iges",
      "dwg",
      "dxf",
      "技术数据",
      "下载",
      "sketchup",
      "solidworks",
      "autocad",
      "revit",
      "尺寸图",
    ],
  },
  {
    id: "ordering-guide",
    title: "Blum 中国产品编号规则与订购手册",
    url: "https://publications.blum.com/2025/miscellaneous/bcn/ordering/zh/",
    summary:
      "Blum 中国产品编号采用字母数字混合编码体系，结构为：[系列前缀][功能代码][规格代码][表面处理后缀]。系列前缀示例：Z38（套装编号）、T51（TANDEMBOX 侧帮）、78Z（TANDEM 导轨）、F（铰链系列）。功能代码标识产品具体功能（如 3E 为 BLUMOTION 导轨、35AI 为带 TIP-ON 抽屉导轨）。规格代码为数字，表示尺寸或力矩等级（如 550A 为 550mm 长度 A 型）。表面处理后缀：Z（镀锌/本色）、N（镍色）、W（白色 RAL 9016）、G（灰色 RAL 7037）、C（碳黑色 RAL 9005）。套装编号（Z38F/Z40H 开头）包含核心组件，配件需单独订购（如 BLUMOTION 阻尼调节螺丝、装饰盖板等）。订购建议：优先使用套装编号（价格优惠且配件兼容），配件单独补订需注明配套套装编号以便核实兼容性。",
    official: true,
    keywords: [
      "产品编号",
      "订购手册",
      "编号规则",
      "套装",
      "z38",
      "z40",
      "t51",
      "blum编号",
      "料号",
      "订货",
      "采购",
      "中国市场",
      "配件",
      "兼容性",
      "表面处理",
    ],
  },
  {
    id: "ordering-combo-guide",
    title: "Blum 套装订购与配件分开订购指南",
    url: "https://publications.blum.com/2025/miscellaneous/bcn/ordering/zh/",
    summary:
      "Blum 产品提供套装订购和配件单订两种采购方式，适用于不同规模和需求的用户。套装订购（套装编号以 Z38F、Z40H、Z45K 等开头）包含完成某一功能所需的全部核心组件，例如 LEGRABOX N 型 500mm 标准套装包含：2 根抽屉侧板、1 副 MOVENTO 导轨（左右各一）、1 套后面板连接件、2 个装饰盖板和 1 套 BLUMOTION 阻尼调节螺丝。套装优势：省去逐件选型的繁琐、价格比单件合计更优惠、配件之间兼容性有保障。配件单订适用于替换单一损坏配件、批量采购时的灵活补货以及套装中不含的可选配件（如 AMBIA-LINE 刀叉盘需单独订购）。单订配件编号格式与套装相同，但不含套装前缀。单订时必须注明配套使用的产品型号和套装编号，以确保配件与现有组件兼容。",
    official: true,
    keywords: [
      "套装订购",
      "配件单订",
      "套装",
      "补货",
      "替换配件",
      "legrabox套装",
      "tandembox套装",
      "配件编号",
      "兼容",
      "z38f",
      "z40h",
      "blum套装",
      "套装内容",
      "可选配件",
      "单独订购",
    ],
  },
  {
    id: "drawer-adjustment",
    title: "Blum 抽屉调节与高度对齐指南",
    url: "https://www.blum.com/us/en/services/e-services/easyassemblyapp/",
    summary:
      "Blum 抽屉系统的调节主要涉及高度、前后位置和倾斜角度三个方面，确保多抽叠加时门面平齐、抽屉操作顺畅。高度调节：LEGRABOX、MERIVOBOX 和 TANDEMBOX 均支持通过侧板上的调节机构实现 ±3mm 的高度微调（用于对齐上下相邻抽屉门面），调节工具为 4mm 内六角扳手。深度调节（前后）：通过导轨侧面的深度调节螺丝实现 ±1mm 的前后微调（用于控制抽屉前脸与柜体平齐程度）。倾斜调节：通过抽屉底部或背部的倾斜调节螺丝实现 -1mm 到 +3mm 的倾斜补偿（用于修正因地面不平导致的抽屉前脸下坠或上翘）。导轨阻尼（BLUMOTION）如感觉关闭速度异常，可通过导轨末端的调节螺丝进行 1~5 档的阻尼强度调整：数字越大阻尼越强（关闭越慢），适合重面板；数字越小阻尼越弱（关闭越快），适合轻面板。",
    official: true,
    keywords: [
      "抽屉调节",
      "高度调节",
      "前后调节",
      "倾斜调节",
      "阻尼调节",
      "blumotion调节",
      "内六角",
      "门面平齐",
      "legrabox",
      "merivobox",
      "tandembox",
      "地面不平",
      "导轨",
      "调节螺丝",
      "阻尼强度",
    ],
  },
  {
    id: "aventos-adjustment",
    title: "AVENTOS 上翻门力矩设置与调节",
    url: "https://www.blum.com/us/en/services/e-services/easyassemblyapp/",
    summary:
      "AVENTOS 上翻门的力矩设置是安装中最关键的步骤，力矩过小会导致门板无法维持开启位置（自行下落），力矩过大会导致开启阻力过大。省力装置的力矩等级选择基于力矩计算公式：力矩(Nm) = 面板重量(kg) × 9.8 × 面板重心高度(m)。计算后对照省力装置等级表（LS/S/M/H/HL）选择最接近且偏大的等级。省力装置本身还提供 ±15% 的微调范围：通过旋转调节螺丝调整弹簧预紧力（顺时针增加力矩，逆时针减小力矩）。安装完成后需要进行开启测试：门板从完全关闭位置手动开启至全开位置，松开后门板应能在任意中间位置稳定悬停（不自行下落也不自行上升），如不符合则需微调力矩。省力装置左右两只必须同时调节且调节量一致，否则会导致门板歪斜。BLUMOTION 阻尼的调节通过 AVENTOS 本体侧面的独立调节螺丝进行，范围 1~5 档，与抽屉阻尼调节方法相同。",
    official: true,
    keywords: [
      "aventos调节",
      "力矩设置",
      "省力装置",
      "力矩调节",
      "力矩计算",
      "开启测试",
      "悬停",
      "blumotion",
      "阻尼调节",
      "弹簧预紧",
      "aventos安装",
      "微调",
      "左右一致",
      "门板歪斜",
      "爱翻",],
  },
  {
    id: "troubleshooting",
    title: "Blum 五金常见安装问题排查指南",
    url: "https://www.blum.com/us/en/services/e-services/easyassemblyapp/",
    summary:
      "Blum 五金常见问题可分为四大类：异响问题、阻尼失效、门缝不均和功能异常。异响问题排查顺序：检查导轨滚轮是否混入异物（木屑、灰尘）→ 检查螺钉是否松动（重新加固至规定扭矩）→ 检查面板是否变形（更换或加固面板）→ 检查阻尼器是否失效（听是否有油液泄漏声）。阻尼失效排查：确认是否为 BLUMOTION 型号（标准型无阻尼）→ 检查温度是否过低（低于 -20°C 硅油黏度剧增）→ 检查阻尼调节档位是否正确（重面板需调高档位）→ 确认阻尼单元是否损坏（不可维修，需更换）。门缝不均排查：重新执行三维调节流程 → 检查门板是否变形 → 检查安装面是否平整 → 检查铰链底座是否安装到位。功能异常（TIP-ON 无反应）：检查门面与侧板间隙是否 ≥ 2mm → 检查面板厚度是否 ≥ 16mm → 检查触发器安装位置是否正确（距面板前缘 37mm）→ 检查面板重量是否在适用范围内。",
    official: true,
    keywords: [
      "排障",
      "排查",
      "故障",
      "异响",
      "阻尼失效",
      "门缝不均",
      "blumotion",
      "tip-on无反应",
      "门板变形",
      "螺钉松动",
      "面板重量",
      "温度影响",
      "调节",
      "铰链",
      "导轨",
    ],
  },
  {
    id: "blumotion-tuning",
    title: "BLUMOTION 阻尼灵敏调节指南",
    url: "https://www.blum.com.cn/cn/zh/products/motion-technologies/blumotion/overview/",
    summary:
      "BLUMOTION 阻尼的调节通过产品本体上的调节螺丝实现，不同产品系列的调节螺丝位置和调节范围略有差异，但调节逻辑一致：旋转调节螺丝改变油路节流孔的开度，从而改变阻尼力。铰链类（CLIP top BLUMOTION）：调节螺丝位于铰链罩杯侧面，1~5 档，数字越大阻尼越强。抽屉导轨类（MOVENTO/TANDEMBOX/LEGRABOX/MERIVOBOX）：调节螺丝位于导轨末端（抽屉拉出方向的最远端），1~5 档，数字越大阻尼越强。上翻门类（AVENTOS 全系列）：调节螺丝位于省力装置侧面，1~5 档，数字越大阻尼越强。调节参考原则：面板重量 5~15kg 推荐 1~2 档（轻阻尼），15~30kg 推荐 3~4 档（标准阻尼），30kg 以上推荐 4~5 档（强阻尼）。如在冬季低温环境（< 5°C）使用，建议将档位调低 1 档以补偿硅油黏度增加导致的阻尼过强；夏季高温（> 35°C）建议将档位调高 1 档以补偿黏度降低导致的阻尼减弱。",
    official: true,
    keywords: [
      "blumotion调节",
      "阻尼调节",
      "灵敏调节",
      "阻尼强度",
      "调节螺丝",
      "节流孔",
      "油路",
      "档位",
      "面板重量",
      "温度补偿",
      "低温",
      "高温",
      "硅油",
      "阻尼力",
      "调节原则",
    ],
  },
  {
    id: "tip-on-tuning",
    title: "TIP-ON 灵敏度调节指南",
    url: "https://www.blum.com.cn/cn/zh/products/motion-technologies/tip-on/overview/",
    summary:
      "TIP-ON 碰碰开的灵敏度调节通过旋转触发器上的调节螺丝实现，调节范围 1~6mm（代表触发器与弹出器之间的有效触发距离），数字越大触发越灵敏（适合轻面板），数字越小触发越不灵敏（适合重面板）。出厂默认值为 3（中等灵敏度）。灵敏度调节原则：面板重量 8~15kg 推荐灵敏度 5~6（按压即开）；15~25kg 推荐灵敏度 3~4；25~40kg 推荐灵敏度 1~2（需稍用力按压）。注意事项：灵敏度不宜调至最高值 6 用于重面板，否则可能导致误触发（轻微触碰即开门）。TIP-ON BLUMOTION 组合系统的灵敏度调节与纯 TIP-ON 系统相同，但需额外确认 BLUMOTION 阻尼档位（与 TIP-ON 灵敏度各自独立调节）。安装后建议用压力计验证实际触发压力是否在 7~10N 范围内，如超出则需调整灵敏度或检查触发器安装位置（标准位置为距面板前缘 37mm）。",
    official: true,
    keywords: [
      "tip-on调节",
      "灵敏度",
      "碰碰开调节",
      "触发距离",
      "触发压力",
      "调节螺丝",
      "灵敏度调节",
      "面板重量",
      "误触发",
      "压力计",
      "7n",
      "10n",
      "弹出器",
      "触发器",
      "安装位置",
    ],
  },
  {
    id: "quality-certification",
    title: "Blum 产品质量与安全认证",
    url: "https://www.blum.com/cn/zh/about-blum/quality/",
    summary:
      "Blum 产品质量管理体系通过 ISO 9001:2015 认证，覆盖从产品设计、原材料采购、生产制造到售后服务的全流程质量管理。耐用性测试方面：铰链产品需通过 LGA 测试（模拟日常使用开合 20 万次，检测结构完整性和功能保持率）和 Blue/Green 防腐测试（24 小时盐雾测试，等效于海边环境使用 5 年）。抽屉导轨需通过满载循环测试（负重 30kg 或 70kg，开合 10 万次，检测滑轨磨损和阻尼衰减）。AVENTOS 上翻门需通过 5 万次开合循环测试（含 BLUMOTION 阻尼状态）。安全标准方面：Blum 产品符合欧盟 EN 标准（EN 15570 铰链、EN 15338 抽屉）、美国 ANSI/BHMA 标准和中国 GB/T 标准（GB/T 3325 家具五金件）。BLUMOTION 阻尼系统还通过 REACH 和 RoHS 环保认证，确保不含铅、汞、镉等有害物质。所有认证文件可通过 Blum 中国官网或授权经销商获取。",
    official: true,
    keywords: [
      "iso 9001",
      "质量认证",
      "lga测试",
      "盐雾测试",
      "耐用性",
      "开合次数",
      "en标准",
      "ansi",
      "gb/t标准",
      "reach",
      "rohs",
      "环保认证",
      "安全标准",
      "防腐",
      "认证文件",
    ],
  },
  {
    id: "environmental-cert",
    title: "Blum 环保合规与可持续认证",
    url: "https://www.blum.com/cn/zh/about-blum/quality/",
    summary:
      "Blum 环保管理体系通过 ISO 14001:2015 认证，致力于在产品全生命周期中减少环境影响。材料合规方面：BLUMOTION 阻尼器中的硅油材料通过 REACH 法规（欧盟化学品注册、评估、授权和限制）认证，不含 SVHC（高关注物质）清单中的物质。Blum 金属产品（铰链、导轨、抽屉侧板）材质为优质冷轧钢，镀锌和电泳处理不含六价铬（Cr6+），符合 RoHS 指令（限制在电子电气设备中使用有害物质）。包装方面：Blum 中国市场的产品包装纸箱采用 100% 再生纸板，外包装印刷使用大豆油墨，减少挥发性有机化合物（VOC）排放。产品回收方面：Blum 在欧洲设有五金件回收计划，将使用后的金属件通过分拣、熔炼再利用（回收率目标 95% 以上）。BLUMOTION 阻尼单元由于含有硅油，需作为特殊废弃物处理，不可混入普通生活垃圾。",
    official: true,
    keywords: [
      "iso 14001",
      "环保",
      "可持续",
      "reach",
      "rohs",
      "六价铬",
      "再生纸板",
      "大豆油墨",
      "voc",
      "回收",
      "硅油",
      "阻尼器处理",
      "有害物质",
      "生命周期",
      "环保认证",
    ],
  },
  {
    id: "product-catalogue",
    title: "Blum 中文综合产品目录",
    url: "https://publications.blum.com/2022/catalogue/zh/toc/",
    summary:
      "Blum 中文产品目录是 Blum 产品的全面技术参考手册，按产品系列分为上翻门系统（AVENTOS HF/HS/HL/HK/HKi 等）、铰链系统（CLIP top BLUMOTION、CLIP top、MODUL 等）、抽屉系统（LEGRABOX、MERIVOBOX、TANDEMBOX）、导轨系统（MOVENTO、TANDEM）、动感技术（BLUMOTION、TIP-ON、TIP-ON BLUMOTION、SERVO-DRIVE）、口袋门系统（REVEGO）、内分隔系统（AMBIA-LINE、ORGA-LINE）、柜体应用（SPACE TOWER、SPACE STEP）、E-SERVICES（配置器、EASY ASSEMBLY、MINIPRESS、BXF）和通用技术信息（选型计算、安装规范、认证标准）。目录提供每个产品的详细技术规格、尺寸图、选型参数表和安装要求。目录为在线版本（Blum publications 平台），支持章节跳转、全文搜索和 PDF 单页下载。该目录是 Blum 中国市场最具权威性的综合技术文档，也是本知识库的核心参考来源。",
    official: true,
    keywords: [
      "blum目录",
      "产品目录",
      "中文目录",
      "技术手册",
      "产品系列",
      "规格",
      "选型参数",
      "尺寸图",
      "安装规范",
      "官方文档",
      "参考文献",
      "权威来源",
      "pdf下载",
      "百隆",
      "blum",
    ],
  },
  {
    id: "blum-contact",
    title: "Blum 中国官方联系渠道",
    url: "https://www.blum.com/cn/zh/contact/",
    summary:
      "Blum 中国总部位于上海市，负责中国大陆市场的销售、技术支持和售后服务。当技术资料与实际产品不符、市场型号命名不明确、或需要官方确认产品规格时，建议通过以下渠道联系 Blum：客服热线（工作时间周一至周五 9:00~17:00）、电子邮件技术支持邮箱、官方微信公众号（Blum 百隆，提供产品查询和授权经销商查询功能）。授权经销商查询可通过官网经销商地图获取，按省份和城市筛选最近的授权销售点。Blum 还在北京、广州、成都和沈阳设有区域办公室，可提供现场技术培训和安装指导服务。对于橱柜厂和家具厂客户，Blum 提供专属客户经理对接服务，包括定期产品培训和现场技术问题响应。",
    official: true,
    keywords: [
      "联系blum",
      "客服",
      "经销商",
      "授权经销商",
      "官方",
      "百隆中国",
      "技术热线",
      "售后服务",
      "区域办公室",
      "培训",
      "客户经理",
      "官方确认",
      "哪里买",
      "咨询",
      "技术支持",
    ],
  },
  {
    id: "cliptop-cup-drilling-35mm",
    title: "CLIP top 35 mm 铰杯孔与固定孔",
    url: "https://www.blum.com/cn/zh/products/hingesystems/clip-top-blumotion/overview/",
    summary: "绝大多数 CLIP top 和 CLIP top BLUMOTION 木门铰链采用直径 35 mm、深度约 11.5–13 mm 的铰杯孔；固定孔中心距通常为 45 mm。实际杯孔深度、孔距和螺钉/INSERTA 固定方式必须按对应铰链型号的技术图纸执行，切勿以通用 35 mm 孔替代型号确认。",
    official: true,
    keywords: ["35mm杯孔", "铰杯孔", "杯孔直径", "杯孔深度", "45mm孔距", "铰链开孔", "hinge cup", "cup drilling", "CLIP top开孔"],
  },
  {
    id: "cliptop-door-thickness-and-cup-distance",
    title: "CLIP top 门厚、杯孔距离与门缝",
    url: "https://publications.blum.com/2022/catalogue/zh/186/",
    summary: "35 mm 杯铰链的适用门厚与最小门缝取决于开门角度、杯孔距离（C 值）、底座高度和盖位。常见木门应用从约 15 mm 起；门越厚、C 值越小或开门角越大，所需门缝通常越大。选型时应使用 Blum 门缝曲线/产品配置器，输入实际门厚和 C 值，不应只按经验预留门缝。",
    official: true,
    keywords: ["门厚范围", "杯孔距离", "C值", "最小门缝", "门缝多少", "35mm铰链", "door thickness", "reveal", "cup distance", "铰链干涉"],
  },
  {
    id: "cliptop-overlay-half-inset-calculation",
    title: "全盖、半盖与内嵌门的盖位计算",
    url: "https://publications.blum.com/2022/catalogue/zh/194/",
    summary: "全盖门覆盖柜侧板；两扇门共用中间侧板时通常选择半盖门；内嵌门位于柜体侧板之间。最终盖位不是仅由铰链名称决定，而由铰链臂形、底座高度、杯孔距离 C、门厚及所需门缝共同决定。生产前应在 Blum 配置器或目录盖位/门缝表中核算，而不是把“全盖=固定数值、半盖=一半”直接套用。",
    official: true,
    keywords: ["全盖怎么算", "半盖怎么算", "内嵌门", "盖位计算", "overlay", "half overlay", "inset", "中柱两扇门", "底座高度", "门缝表"],
  },
  {
    id: "cliptop-opening-angle-selection",
    title: "CLIP top 开门角度与限制器",
    url: "https://www.blum.com/cn/zh/products/hingesystems/clip-top-blumotion/overview/",
    summary: "CLIP top 系统有约 95°、107°/110°、120°及 155°等不同开门角度的型号。相邻柜体、抽屉拉手或墙体会造成碰撞时，应优先按目录选择配套角度限制器；限制器只限制开启角，不能修正错误的门缝、底座高度或门板干涉。",
    official: true,
    keywords: ["开门角度", "95度", "110度", "155度", "角度限制器", "限位器", "开门碰墙", "hinge opening angle", "restriction clip"],
  },
  {
    id: "cliptop-blumotion-deactivation",
    title: "CLIP top BLUMOTION 阻尼启停",
    url: "https://www.blum.com/cn/zh/products/hingesystems/clip-top-blumotion/overview/",
    summary: "CLIP top BLUMOTION 的阻尼会随门重和门板数量自动适配；对轻窄门，部分型号可通过铰链上的开关停用一只或多只铰链的 BLUMOTION，以避免关门过慢或回弹。并非所有型号都提供“0–9”统一阻尼刻度；应以铰链本体标识和该型号安装说明为准。",
    official: true,
    keywords: ["阻尼0到9", "阻尼档位", "关闭阻尼", "轻门关不住", "门回弹", "BLUMOTION开关", "damper deactivation", "soft close too strong"],
  },
  {
    id: "tipon-doors-gap-and-magnetic-latch",
    title: "TIP-ON for doors 门缝与磁吸固定",
    url: "https://www.blum.com/cn/zh/products/motion-technologies/tip-on/overview/",
    summary: "TIP-ON for doors 为机械按压开启方案，门关闭位置由专用磁吸组件保持。触发器安装、前后间隙和弹出距离必须按具体 TIP-ON 型号模板调整；推开距离并非全系列固定值。无拉手门出现按压不弹、误弹或无法闭合，应先检查门缝、磁吸对位、铰链调节和门板翘曲。",
    official: true,
    keywords: ["tip-on感应距离", "弹出距离", "磁吸", "按压不弹", "碰碰开不灵", "误弹", "push to open", "magnetic catch", "无拉手门缝"],
  },
  {
    id: "merivobox-height-and-length",
    title: "MERIVOBOX 侧帮高度与标称长度",
    url: "https://www.blum.com/cn/zh/products/boxsystems/merivobox/overview/",
    summary: "MERIVOBOX 是模块化抽屉箱系统，可组合不同侧帮高度、抽屉长度、前板接口与内抽/高抽配置。订货时必须同时确定标称长度、侧帮高度、左/右侧帮、前板连接件、后板及同步/稳定配件；侧帮高度不能单独推导承重等级，承重应以对应导轨型号的许可值为准。",
    official: true,
    keywords: ["MERIVOBOX高度", "侧帮高度", "抽屉深度", "标称长度", "merivobox尺寸", "抽屉侧板", "drawer side height", "nominal length"],
  },
  {
    id: "merivobox-load-classes",
    title: "MERIVOBOX 导轨承重等级核对",
    url: "https://publications.blum.com/2022/catalogue/zh/78/",
    summary: "MERIVOBOX 的额定动态承重由具体滑轨版本决定，常见项目会遇到 30 kg、40 kg或 70 kg级别，但不应把所有 MERIVOBOX 一概标为同一数值。抽屉实际可承载还受标称长度、柜体结构、安装质量及稳定器配置影响；设计、销售和采购应以产品号对应的目录承重表确认。",
    official: true,
    keywords: ["MERIVOBOX承重", "30kg", "40kg", "70kg", "抽屉承重", "动态承重", "load capacity", "重型抽屉", "导轨等级"],
  },
  {
    id: "legrabox-height-and-length",
    title: "LEGRABOX 规格与高抽配置",
    url: "https://www.blum.com/cn/zh/products/boxsystems/legrabox/overview/",
    summary: "LEGRABOX 为金属抽屉系统，提供不同侧帮高度、标称长度和高抽围栏/金属后板配置，并可配合 AMBIA-LINE 内分隔。高抽的承载和抗侧摆能力取决于完整抽屉构造，不可只订两根侧帮；下单前须核对侧帮、导轨、前板连接件、后板、围栏和所需稳定组件是否齐套。",
    official: true,
    keywords: ["LEGRABOX高度", "LEGRABOX尺寸", "高抽", "围栏", "金属后板", "抽屉侧帮", "legrabox side", "drawer configuration"],
  },
  {
    id: "legrabox-load-capacity",
    title: "LEGRABOX 40 kg 与 70 kg 导轨选型",
    url: "https://publications.blum.com/2022/catalogue/zh/54/",
    summary: "LEGRABOX 配套导轨常见为 40 kg 和 70 kg动态承重等级。70 kg 不是“更重就一定可替换”的通用件：抽屉长度、柜体孔位、稳定器、前板重量及应用类别也必须满足目录规定。涉及石材、金属或超宽前板时，应通过配置器核验整套方案。",
    official: true,
    keywords: ["LEGRABOX承重", "40kg", "70kg", "重型导轨", "抽屉很重", "70公斤抽屉", "load capacity", "heavy duty drawer"],
  },
  {
    id: "movento-vs-tandem",
    title: "MOVENTO 与 TANDEM 隐藏式导轨对比",
    url: "https://www.blum.com/cn/zh/products/runnersystems/overview/",
    summary: "MOVENTO 和 TANDEM 都是 Blum 隐藏式导轨系统。MOVENTO 侧重同步运行与四维调节能力，可与 BLUMOTION、TIP-ON BLUMOTION 或 SERVO-DRIVE 等动感技术组合；TANDEM 提供可靠顺滑的隐藏式运行。具体承重（例如 30 kg、40 kg、60 kg、70 kg）和标称长度因导轨型号而异，应按产品号核对。",
    official: true,
    keywords: ["MOVENTO和TANDEM区别", "movento", "tandem", "隐藏轨", "托底轨", "四维调节", "同步导轨", "30kg", "60kg", "70kg"],
  },
  {
    id: "undermount-runner-installation",
    title: "隐藏式托底轨抽屉安装前提",
    url: "https://www.blum.com/cn/zh/services/e-services/easy-assembly/",
    summary: "MOVENTO/TANDEM 隐藏式托底轨要求抽屉底板、侧板厚度、后板缺口、锁定装置位置和柜体内宽与对应技术图一致。常见“拉不出、推不回、左右不同步”多数来自抽屉箱尺寸、锁定装置或柜体孔位错误，而非导轨本身故障。应使用 EASY ASSEMBLY 中该产品号的钻孔图与安装动画确认。",
    official: true,
    keywords: ["托底轨安装", "隐藏轨安装", "抽屉后板缺口", "锁定装置", "抽屉拉不出", "抽屉推不回", "undermount runner", "locking device", "安装尺寸"],
  },
  {
    id: "movento-adjustment",
    title: "MOVENTO 抽屉前板调节",
    url: "https://www.blum.com/cn/zh/products/runnersystems/movento/overview/",
    summary: "MOVENTO 系统可通过前部锁定装置和对应调节件实现抽屉前板对齐；不同版本支持高度、侧向、倾斜及深度调节的组合并不完全相同。调节前先确认抽屉已正确卡入两侧导轨，且左右导轨标称长度、安装高度一致。不要强拧非本型号的调节件。",
    official: true,
    keywords: ["MOVENTO调节", "抽屉前板不齐", "抽屉高度调节", "侧向调节", "倾斜调节", "深度调节", "drawer adjustment", "locking device"],
  },
  {
    id: "adubo-sortmatic-market-check",
    title: "ADUBO、SORTMATIC 与中国市场供货确认",
    url: "https://www.blum.com/cn/zh/contact/",
    summary: "ADUBO 和 SORTMATIC 属于市场/年代相关的厨房收纳与废物分类解决方案名称，未必在中国大陆当前产品目录持续供应。涉及替换、补件或新项目订货时，应提供旧件照片、产品号和安装尺寸，由 Blum 中国或授权经销商确认可供货型号；不要仅凭名称用当前 AMBIA-LINE 或其他收纳件强行替代。",
    official: true,
    keywords: ["ADUBO", "SORTMATIC", "垃圾桶", "废物分类", "收纳配件", "中国有货吗", "替换件", "维修件", "spare parts"],
  },
  {
    id: "aventos-lift-factor-calculation",
    title: "AVENTOS 翻门力矩（LF）计算",
    url: "https://www.blum.com/cn/zh/products/liftsystems/overview/",
    summary: "AVENTOS 选型以 Lift Factor（LF，开启力矩）为核心：LF 通常按门板重量（含把手）乘以门板高度计算，并与对应型号目录的 LF 范围比对。宽门或分体门还需按目录乘以宽度/铰链系数。不能只按门板重量选支撑臂；计算完成后须在装柜状态以省力装置调节螺丝校准。",
    official: true,
    keywords: ["AVENTOS力矩", "翻门力矩", "LF计算", "上翻门怎么算", "门重乘高度", "lift factor", "power factor", "支撑臂选型"],
  },
  {
    id: "aventos-hk-series-comparison",
    title: "AVENTOS HK、HK-S、HK top 翻板门区别",
    url: "https://www.blum.com/cn/zh/products/liftsystems/aventos-hk-top/overview/",
    summary: "AVENTOS HK、HK-S 和 HK top 均用于单片翻板门，但适配的柜体深度、力矩范围、安装空间和调节方式不同。HK top 为紧凑型翻板门方案；HK-S 面向较轻应用；旧 HK 系列则须按旧目录确认替换兼容性。它们不能仅因外形相似互换，必须按门高、门重、柜深和产品号选型。",
    official: true,
    keywords: ["HK和HK-S区别", "HK top", "AVENTOS HK", "翻板门", "上翻门支撑", "能不能互换", "lift system comparison"],
  },
  {
    id: "aventos-hf-hs-hl-hl-comparison",
    title: "AVENTOS HF、HS、HL 与 HK 的应用边界",
    url: "https://www.blum.com/cn/zh/products/liftsystems/overview/",
    summary: "AVENTOS HF 为折叠上翻门，HS 为上翻门，HL 为平行上翻门，HK/HK top 为翻板门；门板运动轨迹不同，所需顶部/侧部空间也不同。选型应首先由门板结构和开门轨迹决定，再按 LF 范围选省力装置。不能将 HF、HS、HL、HK 的支撑臂或安装孔位混用。",
    official: true,
    keywords: ["HF HS HL HK区别", "AVENTOS HF", "AVENTOS HS", "AVENTOS HL", "折叠上翻", "平行上翻", "翻板门", "开启轨迹"],
  },
  {
    id: "aventos-hk-top-adjustment",
    title: "AVENTOS HK top 省力装置调节",
    url: "https://www.blum.com/cn/zh/products/liftsystems/aventos-hk-top/overview/",
    summary: "AVENTOS HK top 安装后需以两侧省力装置的调节螺丝均衡设置开启力：门应能停在目标位置且不自行下落或猛弹。两侧应使用相同适配范围的省力装置并作近似等量调节；若调到极限仍不能平衡，应重新核对门重、门高和 LF，而非继续加大螺丝力。",
    official: true,
    keywords: ["HK top调节", "上翻门下落", "上翻门弹太快", "弹力不均", "省力装置", "力臂调节", "lift stays adjustment"],
  },
  {
    id: "aventos-servo-drive-compatibility",
    title: "AVENTOS 电动开合与 SERVO-DRIVE",
    url: "https://www.blum.com/cn/zh/products/motion-technologies/servo-drive/overview/",
    summary: "SERVO-DRIVE for AVENTOS 为特定 AVENTOS 系统提供电动辅助开启，可与 BLUMOTION 实现轻触开启、轻柔关闭。电动方案必须按该 AVENTOS 系列的兼容清单配置驱动单元、电源、开关/碰撞保护和安装空间；并非每一款 AVENTOS、旧型号或所有市场都支持。",
    official: true,
    keywords: ["AVENTOS电动", "SERVO-DRIVE", "电动上翻门", "轻触开启", "电源", "驱动单元", "电动开合", "兼容性"],
  },
  {
    id: "revego-system-overview",
    title: "REVEGO 口袋门系统应用与门型",
    url: "https://www.blum.com/cn/zh/products/pocketsystems/revego/overview/",
    summary: "REVEGO 为家具空间提供可推入柜体侧袋的口袋门解决方案，面向单扇或对开前板的隐藏式开启场景。门宽、门高、门厚、门重、柜体深度和侧袋空间必须在对应 REVEGO 版本的技术范围内；不要把它按普通铰链门或移门的尺寸规则设计。",
    official: true,
    keywords: ["REVEGO", "口袋门", "隐藏门", "推入柜体", "口袋门尺寸", "门宽", "pocket system", "空间门"],
  },
  {
    id: "revego-dimensions-and-load",
    title: "REVEGO 尺寸与门重校核",
    url: "https://www.blum.com/cn/zh/products/pocketsystems/revego/overview/",
    summary: "REVEGO 的尺寸和承重上限随版本（例如 duo/uno）、门型与市场版本变化。设计报价时应通过 Blum 配置器输入实际门宽、高、厚、重量和柜体结构获取许可范围与产品清单；将“REVEGO 一律可承 80 kg”或单凭门宽估算均不可靠。",
    official: true,
    keywords: ["REVEGO承重", "REVEGO门宽", "REVEGO门高", "80kg", "口袋门承重", "duo", "uno", "尺寸限制", "load range"],
  },
  {
    id: "revego-installation-preconditions",
    title: "REVEGO 安装前柜体与现场要求",
    url: "https://www.blum.com/cn/zh/services/e-services/easy-assembly/",
    summary: "REVEGO 对柜体方正度、侧袋空间、地面/柜体水平、前板尺寸和安装孔位要求较高。安装前应确认柜体已固定、对角线无明显偏差，并按产品号下载 EASY ASSEMBLY 的安装说明；完成机械调节后再安装饰面和调节门缝。强行在不方正柜体上调门通常会造成运行阻力或门缝失控。",
    official: true,
    keywords: ["REVEGO安装", "口袋门安装", "柜体方正", "门推不进去", "运行阻力", "安装孔位", "EASY ASSEMBLY", "pocket door installation"],
  },
  {
    id: "revego-ordering-checklist",
    title: "REVEGO 订货配件清单核对",
    url: "https://www.blum.com/cn/zh/services/e-services/product-configurator/",
    summary: "REVEGO 项目应以配置器输出的完整 BOM 订货，通常包含左右机构、导向/运行组件、前板连接件、同步或开门组件及与门型匹配的附件。左右件、uno/duo 和门厚相关部件不可凭名称混订；采购时保存配置项目号与 PDF 清单，售后补件才能准确追溯。",
    official: true,
    keywords: ["REVEGO配件", "REVEGO清单", "口袋门BOM", "左右件", "duo配件", "uno配件", "订货", "产品配置器"],
  },
  {
    id: "hinge-adjustment-screws-guide",
    title: "CLIP top 调节螺丝位置与顺序",
    url: "https://www.blum.com/cn/zh/services/e-services/easy-assembly/",
    summary: "CLIP top 的高度通常在底座上调节，侧向（门缝）在铰链臂偏心调节处调节，深度在铰链臂/底座的对应螺丝处调节；不同铰链臂和底座结构会改变具体位置和调节范围。建议先松开/调高度，再调侧缝，最后调深度并复查开合，始终按产品号的安装说明操作。",
    official: true,
    keywords: ["铰链螺丝位置", "高度螺丝", "深度螺丝", "左右螺丝", "门缝不均", "铰链怎么调", "hinge adjustment", "side adjustment", "depth adjustment"],
  },
  {
    id: "hinge-friction-noise-troubleshooting",
    title: "铰链摩擦声与开关门异响排查",
    url: "https://www.blum.com/cn/zh/contact/",
    summary: "铰链异响应依序检查：铰杯、底座和螺钉是否紧固；门板是否与邻门、柜体或拉手发生摩擦；铰链臂是否完全卡入底座；门板是否变形。不要向 BLUMOTION 阻尼器内注油或拆解阻尼单元；若确认单件损坏，应记录产品号后由授权渠道更换。",
    official: true,
    keywords: ["铰链异响", "摩擦声", "开门吱呀", "关门响", "门板摩擦", "铰链松动", "不要加油", "hinge noise", "squeak"],
  },
  {
    id: "drawer-running-troubleshooting",
    title: "抽屉卡顿、不同步与回弹排查",
    url: "https://www.blum.com/cn/zh/services/e-services/easy-assembly/",
    summary: "抽屉卡顿先排除柜体内宽不一致、左右导轨非同型号/长度、锁定装置未卡到位、安装孔偏位和抽屉箱变形。带同步技术的系统还应检查同步件是否按图装齐。切勿通过弯折导轨或向阻尼机构喷油解决；应按产品号安装图复核并更换受损件。",
    official: true,
    keywords: ["抽屉卡", "抽屉异响", "抽屉不同步", "抽屉回弹", "导轨卡顿", "锁定装置没卡", "drawer stuck", "runner noise", "同步杆"],
  },
  {
    id: "blum-installation-tools",
    title: "Blum 安装工具与钻孔辅助",
    url: "https://www.blum.com/cn/zh/services/machines-and-assembly-devices/",
    summary: "常规安装通常需要卷尺/直尺、角尺、水平尺、定位夹具、适配钻头、螺丝刀或扭矩可控电批。35 mm 杯铰链应配套杯孔钻与定位模板；批量生产宜采用 Blum MINIPRESS 等钻孔设备或经确认的模板。工具规格、钻孔深度和螺钉类型须按产品安装图，不应以单一工具清单替代工艺文件。",
    official: true,
    keywords: ["安装工具", "35mm开孔钻", "铰链定位器", "MINIPRESS", "钻孔模板", "电批", "安装夹具", "assembly tools", "boring machine"],
  },
  {
    id: "blum-easy-assembly-videos",
    title: "Blum 官方 EASY ASSEMBLY 安装视频与图纸",
    url: "https://www.blum.com/cn/zh/services/e-services/easy-assembly/",
    summary: "EASY ASSEMBLY 是 Blum 官方装配服务入口，可按产品号查找安装信息、调节步骤、钻孔图和（产品提供时）安装动画/视频。现场人员应优先以产品号检索，而不是用系列名猜测：同一系列不同长度、承重、门型或市场版本的孔位和调节件可能不同。",
    official: true,
    keywords: ["Blum官方视频", "安装视频", "EASY ASSEMBLY", "安装图纸", "钻孔图", "产品号查询", "安装教程", "assembly video"],
  },
  {
    id: "blum-product-number-reading",
    title: "Blum 产品编号识别与订货原则",
    url: "https://www.blum.com/cn/zh/services/e-services/product-configurator/",
    summary: "Blum 产品号常由字母与数字组合，编码会体现系列、功能、版本、长度、承重、表面或左右件等信息，但没有适用于全部品类的单一“逐位解码规则”。采购与售后应以包装标签、产品本体印字和配置器/目录中的完整产品号为准；不要删减后缀或根据相似编号替代。",
    official: true,
    keywords: ["Blum产品编号", "产品号规则", "型号怎么看", "料号", "物料编码", "编号后缀", "part number", "article number", "订货型号"],
  },
  {
    id: "blum-china-availability",
    title: "Blum 中国市场产品可用性确认",
    url: "https://www.blum.com/cn/zh/contact/",
    summary: "官网全球页面、旧目录或海外经销商页面出现的产品不等于中国大陆现货或可订货。中国项目应以 Blum 中国官网、当期中文目录、授权经销商报价和产品号为准；涉及 REVEGO、SERVO-DRIVE、旧系列或特殊颜色时，须在下单前书面确认供货周期、最小订量和替代方案。",
    official: true,
    keywords: ["中国市场", "国内有货吗", "Blum中国", "供货周期", "最小订量", "现货", "授权经销商", "availability China", "能订到吗"],
  },
  {
    id: "blum-packaging-and-spares",
    title: "Blum 包装单位、配件包与维修件",
    url: "https://www.blum.com/cn/zh/services/e-services/product-configurator/",
    summary: "Blum 的包装单位（PU）、是否成对销售、左右件、螺钉/连接件是否另购，均以产品号目录行和包装标签为准。维修时先保留旧件完整产品号、左右方向、长度和失效照片；阻尼器、锁定装置、盖帽、前板连接件等能否单独供应取决于系列和市场，不能默认“一个铰链包装含全部底座和螺钉”。",
    official: true,
    keywords: ["包装单位", "PU", "配件包", "维修件", "备件", "一包多少", "左右件", "是否含螺丝", "spare part", "packaging unit"],
  },
  {
    id: "consumer-drawer-noise-diagnosis",
    title: "消费者：抽屉异响、卡顿或关闭不轻柔的排查顺序",
    url: "https://www.blum.com/cn/zh/services/e-services/easy-assembly/",
    summary: "先清空抽屉并缓慢开关，区分导轨摩擦、前板碰撞和柜内物品碰撞；再确认抽屉两侧完全推入、左右导轨同长度同型号、锁定装置已卡紧。用软刷清除轨道碎屑后复测。不要向 BLUMOTION 阻尼器喷油、不要掰直导轨；仍有金属刮擦、明显间隙或无法闭合时，拍下产品号和故障视频，由授权服务商按型号更换。",
    official: true,
    keywords: ["抽屉响", "抽屉吱吱响", "抽屉卡", "抽屉涩", "抽屉关不轻", "抽屉不好拉", "抽斗卡住", "滑道响", "百隆抽屉异响", "drawer noise", "drawer stuck"],
  },
  {
    id: "consumer-loose-hinge-adjustment",
    title: "消费者：铰链松动与门板松垮的安全调节",
    url: "https://www.blum.com/cn/zh/services/e-services/easy-assembly/",
    summary: "先扶住门板，检查铰杯固定螺钉、底座螺钉是否松动；用匹配螺丝刀分次拧紧，避免过拧造成板材滑牙。螺钉紧固后仍歪斜，再按“高度—侧向—深度”每次约 1/4 圈微调并合门复核。若螺钉在板内空转、铰杯裂开或底座变形，应停止使用并维修板材/更换同产品号部件。",
    official: true,
    keywords: ["铰链松了", "合页松", "柜门松垮", "门铰松动", "螺丝滑牙", "铰链怎么紧", "门板晃", "百隆合页松", "loose hinge"],
  },
  {
    id: "consumer-door-sag-adjustment",
    title: "消费者：柜门下垂的调节方法",
    url: "https://publications.blum.com/2022/catalogue/zh/194/",
    summary: "先确认所有铰链均已扣入底座并紧固；两只以上铰链的门板，下垂通常先用底座高度调节把门整体上移，再以侧向调节恢复均匀门缝。每次只调一个方向、约 1/4 圈，关门检查上缝和中缝。若门板翘曲、超过铰链允许门重/门宽，或调节到极限仍下垂，应复核铰链数量和门板结构。",
    official: true,
    keywords: ["门板下垂", "柜门往下掉", "橱柜门下坠", "门歪", "门高低不齐", "合页调高", "柜门掉角", "door sag", "hinge height adjustment"],
  },
  {
    id: "consumer-hinge-corrosion-care",
    title: "消费者：铰链生锈、氧化后的处理",
    url: "https://www.blum.com/cn/zh/contact/",
    summary: "用干软布去除水汽和表面灰尘，保持浴室柜、水槽柜通风并修复持续渗水源；切勿用钢丝球、强酸/强碱、含氯清洁剂或浸泡方式处理铰链。出现锈蚀点、镀层起皮、阻尼异常或转动发涩时，应记录完整产品号并更换受影响件；腐蚀不能靠喷漆或加油恢复安全和阻尼性能。",
    official: true,
    keywords: ["铰链生锈", "合页锈了", "百隆铰链锈", "五金氧化", "柜门合页生锈", "铰链发黑", "浴室柜铰链", "hinge rust", "corrosion"],
  },
  {
    id: "consumer-drawer-runner-replacement",
    title: "消费者：抽屉滑轨损坏后的替换信息采集",
    url: "https://www.blum.com/cn/zh/services/e-services/product-configurator/",
    summary: "替换前取下抽屉，拍摄左右导轨、锁定装置和包装/本体印字；记录产品号、标称长度、左右件、承重等级、抽屉箱结构及是否带 BLUMOTION、TIP-ON 或 SERVO-DRIVE。不要只按“长度相同”购买通用轨：MOVENTO、TANDEM、METABOX 和抽屉箱系统的孔位及连接件不同。安装后空载开关 10 次、再逐步加载测试。",
    official: true,
    keywords: ["抽屉滑轨坏了", "导轨怎么换", "百隆导轨更换", "抽屉轨道断了", "滑道坏", "抽屉拉不出来", "托底轨换", "drawer runner replacement", "换滑轨"],
  },
  {
    id: "consumer-door-wont-close",
    title: "消费者：柜门关不上、关不紧的检查",
    url: "https://www.blum.com/cn/zh/services/e-services/easy-assembly/",
    summary: "先清除柜内顶住门板的物品，检查拉手、相邻门和台面是否碰撞；再确认铰链臂完全扣入底座、门板没有翘曲。门板前凸时用深度调节小幅后移，双门中缝过紧时用侧向调节释放，每次约 1/4 圈并复测。TIP-ON 门还要检查磁吸对位；不得拆开阻尼器或强压关门。",
    official: true,
    keywords: ["柜门关不上", "柜门关不紧", "门关不严", "橱柜门弹开", "门合不上", "柜门顶住", "关门反弹", "door will not close", "门留缝"],
  },
  {
    id: "consumer-damper-failure-signs",
    title: "消费者：BLUMOTION 阻尼异常的表现与原因",
    url: "https://www.blum.com/cn/zh/products/motion-technologies/blumotion/overview/",
    summary: "阻尼异常常表现为关门最后一段突然撞击、门在半程停滞/回弹，或轻窄门关得过慢。先确认铰链数量、门板重量和所有铰链的 BLUMOTION 启停状态一致；轻门仅在该型号允许时可停用一只阻尼。若单只铰链无阻尼、漏油、壳体裂损或不同铰链动作差异明显，应更换同型号铰链，不要拆修阻尼盒。",
    official: true,
    keywords: ["阻尼失效", "百隆阻尼坏了", "关门砰", "缓冲没了", "铰链不缓冲", "门回弹", "soft close broken", "blumotion failure", "关门太快"],
  },
  {
    id: "consumer-hardware-cleaning",
    title: "消费者：Blum 五金的日常清洁与维护",
    url: "https://www.blum.com/cn/zh/contact/",
    summary: "日常使用微湿软布擦拭后立即擦干；油污可先在布上使用少量中性清洁剂，避免清洁液直接喷进导轨、阻尼器、电动部件和铰链缝隙。禁止磨料、钢丝球、强溶剂、强酸碱和含氯清洁剂。每 6–12 个月检查固定螺钉、门缝与抽屉运行；发现水渍锈蚀或结构松动应先处理原因再维修。",
    official: true,
    keywords: ["百隆怎么清洁", "五金清洁", "铰链保养", "导轨清理", "能不能加油", "柜门合页清洗", "清洁剂", "hardware cleaning", "drawer maintenance"],
  },
  {
    id: "consumer-retrofit-old-furniture",
    title: "消费者：老家具能否改装 Blum 配件",
    url: "https://www.blum.com/cn/zh/services/e-services/product-configurator/",
    summary: "老家具可以评估改装，但不能以“35 mm 杯孔相同”直接判定兼容。需测量门厚、杯孔直径/深度、C 值、柜侧板、门缝、抽屉内宽和旧件孔位，并确认板材仍有握钉力。旧铰链或旧导轨的孔位可能不适配现行产品；建议先由安装人员用单门/单屉试装，再决定整套改造。",
    official: true,
    keywords: ["老家具换百隆", "旧柜改百隆", "旧铰链能换吗", "老橱柜改造", "能装百隆吗", "旧抽屉换导轨", "翻新家具五金", "retrofit", "replacement compatibility"],
  },
  {
    id: "consumer-uneven-door-gaps",
    title: "消费者：橱柜门缝不均匀的调节顺序",
    url: "https://publications.blum.com/2022/catalogue/zh/194/",
    summary: "先从基准门开始：用高度调节对齐上下边，再用侧向调节把门缝调成视觉均匀，最后用深度调节使门面齐平。双门应两扇交替小幅调整，避免只把一扇调到极限。调节前检查柜体是否水平、门板是否翘曲；门缝目标受门厚、铰链型号和设计要求影响，需按图纸/产品资料确认。",
    official: true,
    keywords: ["门缝不均", "橱柜门缝", "柜门缝一边大", "双门不齐", "门板不平", "门缝怎么调", "柜门高低", "uneven reveal", "door gap"],
  },
  {
    id: "consumer-replace-or-adjust",
    title: "消费者：判断五金应调节、维修还是更换",
    url: "https://www.blum.com/cn/zh/contact/",
    summary: "门缝偏差、螺钉轻微松动和抽屉未卡到位通常先按说明调节；出现裂纹、变形、锈蚀穿孔、阻尼漏油、导轨部件脱落、锁定装置破损或螺钉持续空转时，应停止重载使用并更换。更换前保留产品号、左右方向、长度和照片。不要以不同系列的“看起来相似”零件混搭。",
    official: true,
    keywords: ["五金要不要换", "铰链坏了吗", "导轨需要换", "什么时候换合页", "阻尼漏油", "抽屉轨道变形", "配件损坏", "repair or replace"],
  },
  {
    id: "consumer-tip-on-troubleshooting",
    title: "消费者：TIP-ON 按压不灵敏、误弹的处理",
    url: "https://www.blum.com/cn/zh/products/motion-technologies/tip-on/overview/",
    summary: "先在门板指定按压区轻推测试，清除门板与柜体间异物；检查门缝、磁吸件/触发器前后位置、铰链调节和门板翘曲。TIP-ON 要有合适关闭位置与间隙，门被台面、拉手或邻门顶住也会影响触发。不可任意缩短触发器或用胶垫硬垫；按产品号模板复位仍无效时更换对应组件。",
    official: true,
    keywords: ["TIP-ON不灵", "碰碰开不灵", "按压不开", "一碰就开", "柜门误弹", "无把手门打不开", "tipon失灵", "push to open not working", "感应不灵敏"],
  },
  {
    id: "consumer-blumotion-adjustment",
    title: "消费者：BLUMOTION 力度与启停的正确理解",
    url: "https://www.blum.com/cn/zh/products/hingesystems/clip-top-blumotion/overview/",
    summary: "大多数 CLIP top BLUMOTION 通过自适应阻尼工作，不存在通用的“力度旋钮”可随意调大调小。对轻窄门，部分型号允许通过铰链开关停用一只或多只阻尼；操作前须看清本体标识和安装说明。门仍下落或猛弹，应复核门重、铰链数量和型号，不应靠强拧无关螺丝或拆开阻尼机构处理。",
    official: true,
    keywords: ["BLUMOTION怎么调", "百隆阻尼调节", "阻尼力度", "阻尼太重", "阻尼太轻", "软关闭调节", "blumotion adjustment", "soft close adjustment"],
  },
  {
    id: "consumer-door-removal-reinstallation",
    title: "消费者：CLIP 铰链门板拆卸与重装",
    url: "https://www.blum.com/cn/zh/products/hingesystems/clip-top-blumotion/overview/",
    summary: "拆卸前扶稳门板并打开到便于操作的角度，按 CLIP 铰链臂的释放卡扣使铰链从底座脱开；不要扭拽门板。重装时将每只铰链对准底座前端后压入，确认扣合，再轻拉验证每只均锁定。两人操作重门或高门；装回后检查门缝、开合和阻尼，不确定型号时先查产品号说明。",
    official: true,
    keywords: ["柜门怎么拆", "铰链门板拆卸", "百隆铰链拆", "CLIP怎么卸", "柜门装回去", "合页怎么扣", "门板重装", "remove cabinet door", "clip hinge release"],
  },
  {
    id: "consumer-authorized-purchase-authenticity",
    title: "消费者：购买渠道与真伪核验",
    url: "https://www.blum.com/cn/zh/contact/",
    summary: "优先从 Blum 中国、其公开联系渠道确认的授权经销商或提供可追溯发票的家具品牌购买。核验时保存包装标签、完整产品号、批次/条码、购买凭证和本体标识；仅凭 Logo、低价或包装颜色不能断定真伪。对疑似假货、错货或工程尾货，应向 Blum 中国/授权渠道提交照片和产品号确认，勿自行拆改后再申诉。",
    official: true,
    keywords: ["百隆真假", "百隆正品", "Blum授权经销商", "百隆在哪里买", "铰链真伪", "假百隆", "产品防伪", "authorized dealer", "authenticity"],
  },
  {
    id: "design-runner-load-selection",
    title: "设计：按承重、长度与使用频次选择导轨",
    url: "https://www.blum.com/cn/zh/products/runnersystems/overview/",
    summary: "计算抽屉箱、前板、把手和常态收纳物总质量并预留工况余量，再按标称长度、额定动态承重、抽屉宽度/稳定性和动感技术选具体导轨。锅具重抽、宽抽和高频商用抽不能只按“30/40/70 kg”替换；最终以产品号目录许可值及完整抽屉构造核验。",
    official: true,
    keywords: ["导轨怎么选", "抽屉承重选型", "重型抽屉", "锅具抽", "70公斤导轨", "抽屉滑轨承重", "runner load selection", "宽抽导轨"],
  },
  {
    id: "design-hinge-cup-distance-door-width",
    title: "设计：门宽、门重与铰杯孔距离的联动",
    url: "https://publications.blum.com/2022/catalogue/zh/186/",
    summary: "门宽/门高增大时，铰链数量和间距需随门重、板材、把手及使用频次增加；铰杯孔距离 C 值与门厚、开门角、盖位和最小门缝共同决定。不能用单一门宽规则；应按对应铰链门重—门高图、门缝曲线和实际 C 值确定并交付加工数据。",
    official: true,
    keywords: ["门宽铰链数量", "铰链几个", "C值和门宽", "铰杯距离", "门重选铰链", "大门板合页", "hinge quantity", "cup distance", "door weight chart"],
  },
  {
    id: "design-glass-aluminium-hinges",
    title: "设计：玻璃门、铝框门的铰链选型",
    url: "https://www.blum.com/cn/zh/products/hingesystems/overview/",
    summary: "玻璃门和铝框门不能套用木门 35 mm 杯孔铰链。先确认门框截面、玻璃厚度、固定方式、门重、开门角和门缝，再选对应的玻璃/铝框专用铰链或安装板。图纸必须注明门框系统与固定件，避免现场临时打孔导致玻璃破裂或框材变形。",
    official: true,
    keywords: ["玻璃门铰链", "铝框门铰链", "窄铝框", "玻璃柜门合页", "铝合金门合页", "玻璃门怎么装", "glass door hinge", "aluminium frame hinge"],
  },
  {
    id: "design-handleless-opening-options",
    title: "设计：暗藏门、无拉手门的开合方案",
    url: "https://www.blum.com/cn/zh/products/motion-technologies/overview/",
    summary: "无拉手门可按体验选择机械 TIP-ON、带 BLUMOTION 的按压开合、电动 SERVO-DRIVE，或斜切/凹槽拉手。选择前确认门重、门缝、可用电源、停电时手动操作、儿童误触和预算；大门板和高频场景要核验触发与回弹。门用 TIP-ON 与抽屉用部件不可互换。",
    official: true,
    keywords: ["无拉手方案", "暗藏门", "免把手柜门", "TIP-ON还是电动", "隐形门五金", "无把手开门", "handleless", "push to open design", "SERVO-DRIVE"],
  },
  {
    id: "design-high-cabinet-lift-factor",
    title: "设计：高柜上翻门的力矩与空间校核",
    url: "https://www.blum.com/cn/zh/products/liftsystems/overview/",
    summary: "先按门板重量（含把手）×门高计算 Lift Factor，并按对应 AVENTOS 规定考虑宽度或门型系数；再校核柜体顶部空间、开启轨迹、相邻吊顶/灯具和可触及高度。LF 必须落在省力装置范围且左右成对匹配；仅按门重或门高单独选支撑臂会造成下落、猛弹或无法停留。",
    official: true,
    keywords: ["高柜上翻门", "上翻门力矩", "AVENTOS高柜", "LF怎么计算", "翻门停不住", "吊柜翻门选型", "lift factor", "lift system planning"],
  },
  {
    id: "design-island-hardware-planning",
    title: "设计：岛台/中岛柜的五金方案",
    url: "https://www.blum.com/cn/zh/products/boxsystems/overview/",
    summary: "岛台双面使用、抽屉宽且常装锅具，应分别核算两侧开门净空、通道宽度、抽屉承重、宽抽抗侧摆、内部分隔和电源/管线避让。面向走道的抽屉可用 BLUMOTION 降低撞击；无拉手方案还要避免双侧误触。柜体须在台面安装前固定并保持方正。",
    official: true,
    keywords: ["岛台五金", "中岛抽屉", "双面柜", "厨房岛台设计", "宽抽", "锅具收纳", "island hardware", "kitchen island drawer"],
  },
  {
    id: "design-open-kitchen-dust-moisture",
    title: "设计：开放式厨房的防尘、防油与通风考虑",
    url: "https://www.blum.com/cn/zh/contact/",
    summary: "把油烟、水汽和高频使用纳入结构设计：避免让导轨、铰链长期直面灶台飞溅，给水槽柜留检修与通风条件，并用完整前板/门缝方案减少碎屑进入抽屉。五金不是密封防尘件，不能承诺完全防油防水；须结合抽油烟、柜体封边和日常清洁方案。",
    official: true,
    keywords: ["开放式厨房五金", "防尘导轨", "防油铰链", "水槽柜五金", "厨房油烟", "防潮柜门", "open kitchen", "dust moisture"],
  },
  {
    id: "design-child-safety-cabinet-solutions",
    title: "设计：儿童安全场景的柜门与抽屉方案",
    url: "https://www.blum.com/cn/zh/products/motion-technologies/blumotion/overview/",
    summary: "BLUMOTION 可减缓闭合撞击，但不是儿童防夹或防开启装置。药品、清洁剂和刀具应配置独立安全锁并置于高位/受控柜体，避免把 TIP-ON 当作安全措施；重型抽屉须核验满载稳定性和柜体固定。方案中明确安全锁、柜体锚固和使用提醒责任。",
    official: true,
    keywords: ["儿童安全柜", "防夹手", "儿童锁柜门", "TIP-ON儿童", "厨房安全", "抽屉防倾倒", "child safety", "cabinet lock"],
  },
  {
    id: "design-museum-exhibition-requirements",
    title: "设计：博物馆、展厅柜体的特殊要求",
    url: "https://www.blum.com/cn/zh/contact/",
    summary: "展陈柜体常涉及保安锁、玻璃安全、低噪音、频繁维护、文物环境控制和项目验收标准。Blum 五金可作为运行组件，但不能替代防盗、密封、耐火或文保认证。设计前取得项目规范，按门重、门型和维护频率选型，并由总包/展柜厂确认合规与可维修性。",
    official: true,
    keywords: ["博物馆柜五金", "展厅柜门", "展柜铰链", "低噪音展柜", "文物柜", "玻璃展柜", "museum cabinet", "exhibition hardware"],
  },
  {
    id: "design-custom-furniture-tolerances",
    title: "设计：定制家具尺寸配合与公差交付",
    url: "https://www.blum.com/cn/zh/services/e-services/easy-assembly/",
    summary: "把柜体内宽、板厚、门厚、门缝、杯孔 C 值、导轨安装高度、前板搭接和基准面写进加工图；不可只给效果图或成品外尺寸。先选准确产品号，再导出对应钻孔图和 CAD 数据。现场复尺若柜体方正度、墙地面水平超出可调范围，应先修正柜体。",
    official: true,
    keywords: ["定制家具公差", "柜体尺寸配合", "门缝加工图", "板厚五金", "柜体内宽", "家具深化", "custom furniture tolerance", "cabinet dimensions"],
  },
  {
    id: "install-hinge-cup-template",
    title: "安装：35 mm 铰杯孔模板的使用流程",
    url: "https://www.blum.com/cn/zh/services/machines-and-assembly-devices/",
    summary: "确认产品号对应的杯孔直径、杯深和固定孔距后，将模板以门边基准夹紧；先在废料试钻，检查 C 值、孔深和固定孔位置。正式钻孔保持钻头垂直并设限深，避免穿透门面；钻后清屑再装铰杯。模板只是定位辅助，不能替代产品号钻孔图。",
    official: true,
    keywords: ["铰链模板怎么用", "35mm杯孔模板", "合页开孔定位", "杯孔钻", "铰链打孔", "门板钻孔", "hinge jig", "cup drilling template"],
  },
  {
    id: "install-overlay-half-inset-changeover",
    title: "安装：全盖、半盖、内嵌门的现场切换边界",
    url: "https://publications.blum.com/2022/catalogue/zh/194/",
    summary: "全盖、半盖、内嵌由铰链臂形、底座高度、C 值、门厚和门缝共同形成，不是仅调一颗螺丝就能互换。改门型前先确认两扇门是否共用侧板、现有铰链/底座产品号和门缝曲线；需要换铰链臂或底座时按完整组合替换，改后做开门干涉和门缝复核。",
    official: true,
    keywords: ["全盖改半盖", "半盖改内嵌", "铰链盖位切换", "0盖1盖2盖", "柜门全盖", "内嵌门安装", "overlay change", "half overlay"],
  },
  {
    id: "install-movento-preinstallation",
    title: "安装：MOVENTO 导轨预装与抽屉挂装技巧",
    url: "https://www.blum.com/cn/zh/services/e-services/easy-assembly/",
    summary: "先核对左右导轨产品号、标称长度和安装高度一致，以柜体前沿/后定位孔为同一基准固定；柜体对角线和内宽异常先整改。抽屉挂装时同时对正两侧导轨，平推至锁定装置完全扣合，再空载开关数次。不要以敲击、硬推或弯折导轨方式处理无法挂入。",
    official: true,
    keywords: ["MOVENTO预装", "movento安装", "托底轨挂抽", "抽屉挂不上", "锁定装置", "隐藏轨预装", "runner preinstallation", "movento fitting"],
  },
  {
    id: "install-merivobox-side-adjustment",
    title: "安装：MERIVOBOX 侧帮高度与箱体构造确认",
    url: "https://www.blum.com/cn/zh/products/boxsystems/merivobox/overview/",
    summary: "MERIVOBOX 的侧帮高度是系统规格，不应在现场任意裁切侧帮来适配高度；先按产品号确认侧帮高度、标称长度、后板高度、前板连接件和所需围栏/稳定组件。若柜体尺寸改变，应重新按配置器选择对应构造；切割会破坏孔位、表面与运行安全，除非该部件技术资料明确允许。",
    official: true,
    keywords: ["MERIVOBOX侧帮裁切", "魅宝侧板切短", "抽屉侧帮高度", "MERIVOBOX安装", "侧帮能切吗", "抽屉箱改尺寸", "merivobox side height"],
  },
  {
    id: "install-level-and-square-check",
    title: "安装：确认柜体水平、垂直与方正的方法",
    url: "https://www.blum.com/cn/zh/services/e-services/easy-assembly/",
    summary: "安装五金前以水平尺检查柜体底板/导轨基准线，以角尺检查侧板与底板，以对角线比较检查方正；两条对角线差、柜体内宽前后差和侧板扭曲应记录并按项目公差处理。导轨、底座只能补偿有限门缝误差，不能纠正明显柜体变形。",
    official: true,
    keywords: ["柜体怎么找平", "柜体方正", "导轨水平", "安装水平尺", "对角线误差", "柜子不方", "cabinet level", "cabinet square"],
  },
  {
    id: "install-door-drilling-layout",
    title: "安装：门板打孔定位与试装",
    url: "https://www.blum.com/cn/zh/services/e-services/easy-assembly/",
    summary: "从最终门边基准标出杯孔中心和固定孔，以产品号图纸确认 C 值、杯深、孔距和螺钉方式；先在同批板材试钻、试装并检查最小门缝与开门干涉。批量加工前锁定首件；不可把不同门厚、不同铰链角度或铝框/玻璃门的孔位套用到同一模板。",
    official: true,
    keywords: ["门板打孔定位", "铰链孔怎么定位", "杯孔中心", "门板开孔图", "首件试装", "铰链加工", "door drilling layout", "hinge boring"],
  },
  {
    id: "install-multiple-door-alignment",
    title: "安装：多门板对齐的基准与调节顺序",
    url: "https://publications.blum.com/2022/catalogue/zh/194/",
    summary: "先固定柜体基准门，再从上到下或从中心向两侧逐门调整；每扇门依次调高度、侧缝、深度，双门中缝需两边交替小幅调节。使用垫片/直尺检查门面共面，最后全开全关检查拉手、台面和相邻抽屉干涉。不要只调最后一扇门来掩盖前面累计误差。",
    official: true,
    keywords: ["多门板对齐", "一排柜门调平", "双门中缝", "柜门排齐", "门板共面", "铰链批量调节", "multiple door alignment"],
  },
  {
    id: "install-post-installation-functional-test",
    title: "安装：安装后的功能测试清单",
    url: "https://www.blum.com/cn/zh/services/e-services/easy-assembly/",
    summary: "先空载连续开关门/抽屉至少 10 次，确认无刮擦、异响、回弹或松脱；再检查门缝、前板齐平、抽屉全行程、BLUMOTION/TIP-ON/SERVO-DRIVE 功能。随后按预计物品逐步加载，复查柜体固定、螺钉和门板停留。将产品号、调节结果和异常视频交付给售后留档。",
    official: true,
    keywords: ["安装后测试", "抽屉验收", "柜门功能测试", "五金调试", "安装验收清单", "开关十次", "functional test", "installation checklist"],
  },
  {
    id: "install-common-errors-correction",
    title: "安装：常见错误与纠正路径",
    url: "https://www.blum.com/cn/zh/services/e-services/easy-assembly/",
    summary: "高频错误包括左右导轨混用、标称长度不一致、锁定装置未扣、铰链未完全卡入底座、杯孔过深/偏位和柜体未找平。纠正顺序为：停止强行运行，核对产品号和图纸，恢复基准尺寸/孔位，再重新挂装并做功能测试。禁止通过加垫片、强拧阻尼或弯折轨道掩盖结构错误。",
    official: true,
    keywords: ["安装错误", "导轨装反", "铰链没扣上", "抽屉装错", "杯孔打歪", "五金返工", "installation mistake", "runner installed wrong"],
  },
  {
    id: "install-original-tools-selection",
    title: "安装：Blum 原厂工具与使用边界",
    url: "https://www.blum.com/cn/zh/services/machines-and-assembly-devices/",
    summary: "现场可用模板、定位夹具、35 mm 杯钻、限深装置、扭矩可控电批、水平/角尺；批量加工可评估 MINIPRESS、EASYSTICK 等设备。工具选择须跟随产品号加工图、产能和首件验证，原厂工具也不能替代孔位数据与设备校准。电批应先在试件设定扭矩，避免板材滑牙。",
    official: true,
    keywords: ["Blum原厂工具", "百隆安装工具", "铰链定位夹具", "电批扭矩", "杯孔设备", "钻孔设备", "Blum tools", "assembly device"],
  },
  {
    id: "procurement-product-number-decoding",
    title: "采购：Blum 产品号的正确解读方式",
    url: "https://www.blum.com/cn/zh/services/e-services/product-configurator/",
    summary: "产品号中的字母/数字会关联系列、功能、版本、长度、承重、表面或左右件，但不存在覆盖全部品类的通用逐位解码表。采购应以包装标签、本体印字、当期目录和配置器的完整产品号核对；不得删除后缀、凭相似前缀替代，特别是左右件、长度和动感技术版本。",
    official: true,
    keywords: ["Blum编码规则", "产品号怎么读", "料号解析", "物料号规则", "型号后缀", "百隆型号怎么看", "part number decoding", "article number"],
  },
  {
    id: "procurement-product-number-specification",
    title: "采购：用产品号查询规格的步骤",
    url: "https://www.blum.com/cn/zh/services/e-services/product-configurator/",
    summary: "以完整产品号在 Blum 产品配置器、中文目录或授权经销商系统查询，逐项确认品类、左右件、标称长度、承重、颜色/表面、包装单位、必配连接件和市场可用性。若产品号来自旧件，需同时提交照片和安装尺寸；检索不到时不可依据名称猜测新型号，应请官方渠道确认替换关系。",
    official: true,
    keywords: ["料号查规格", "产品号查询", "百隆型号查尺寸", "用料号查配件", "型号查承重", "旧件查型号", "part number lookup", "specification query"],
  },
  {
    id: "procurement-packaging-moq-confirmation",
    title: "采购：标准包装与最小起订量确认",
    url: "https://www.blum.com/cn/zh/contact/",
    summary: "包装单位（PU）、是否成对供应、散件可售性和最小起订量均取决于产品号、渠道与中国市场供应策略。询价单应写明完整产品号、数量、项目地点和到货日期，并要求经销商书面回传 PU、MOQ、交期、税运条件及缺件说明；不要把样册图中的单件数量当作实际下单单位。",
    official: true,
    keywords: ["百隆起订量", "MOQ", "标准包装", "一包多少", "散件购买", "包装单位PU", "最小订货量", "packaging unit", "minimum order"],
  },
  {
    id: "procurement-authorized-dealer-china",
    title: "采购：中国区授权经销商查询与询价留痕",
    url: "https://www.blum.com/cn/zh/contact/",
    summary: "通过 Blum 中国官网联系入口确认所在区域的授权销售/经销渠道，不以搜索广告、店铺自称或低价截图作为授权证明。工程询价应保留联系人、报价日期、完整产品号、PU、交期、保修条件和发票主体；跨区域供货、特殊色和旧系列要书面确认售后责任。",
    official: true,
    keywords: ["百隆中国经销商", "授权经销商查询", "Blum代理商", "哪里采购百隆", "中国授权", "百隆报价", "authorized dealer China", "distributor"],
  },
  {
    id: "procurement-project-lead-time",
    title: "采购：工程项目供货周期的拆解",
    url: "https://www.blum.com/cn/zh/contact/",
    summary: "工程交期不应只问“有没有货”，而要按确认产品号、报价锁定、订单生效、备货/进口、分拣配套、运输和现场验收拆解。对 REVEGO、SERVO-DRIVE、特殊颜色、旧系列和大批量导轨设置替代方案与安全库存；未经渠道书面确认，不要将全球官网展示或口头预计日期写入施工承诺。",
    official: true,
    keywords: ["百隆交期", "工程供货周期", "项目五金到货", "交货期", "特殊色交期", "REVEGO交期", "lead time", "project supply"],
  },
  {
    id: "procurement-kit-vs-loose-parts",
    title: "采购：配件包与散件的区别及 BOM 核对",
    url: "https://www.blum.com/cn/zh/services/e-services/product-configurator/",
    summary: "配件包可能只含某一功能组件，抽屉/上翻门/口袋门整套通常还需左右件、导轨或省力装置、前板连接件、后板/同步件、螺钉或电源等。下单按配置器输出的 BOM 逐行核对数量、左右、PU 和是否已含，不要把“套装”理解为完整可安装系统；到货时按标签分箱复点。",
    official: true,
    keywords: ["配件包和散件", "百隆套装", "BOM漏件", "抽屉配件清单", "五金缺件", "整套包含什么", "kit vs loose parts", "BOM check"],
  },
  {
    id: "procurement-sample-and-volume-pricing",
    title: "采购：样品、项目价与批量价的边界",
    url: "https://www.blum.com/cn/zh/contact/",
    summary: "样品价、零售价、项目报价和批量报价通常对应不同数量、产品组合、交付地点、付款、税运和有效期，不能互相推算。询价时提供年度/项目预测量与准确 BOM，要求报价标明币种、含税/运费、PU、阶梯数量、有效期与样品是否可抵扣；批准样品前核对其产品号与量产料完全一致。",
    official: true,
    keywords: ["百隆样品价", "批量价格", "工程价", "项目报价", "阶梯价", "样品能抵扣吗", "volume pricing", "sample price"],
  },
  {
    id: "procurement-counterfeit-verification",
    title: "采购：假货识别与正品验证流程",
    url: "https://www.blum.com/cn/zh/contact/",
    summary: "验货保存外箱与内包装标签、完整产品号、批次/条码、发票和本体照片，并与确认渠道/配置器资料交叉核对；Logo、包装颜色或单一外观不能作为唯一判据。疑似假货、串货或错货时先隔离批次、不安装不拆改，向 Blum 中国或授权渠道提交采购凭证和照片确认。",
    official: true,
    keywords: ["采购假货", "百隆验货", "正品验证", "假百隆识别", "防伪查询", "串货", "counterfeit check", "authenticity verification"],
  },
  {
    id: "procurement-original-vs-compatible",
    title: "采购：Blum 原厂件与兼容品的风险比较",
    url: "https://www.blum.com/cn/zh/services/e-services/product-configurator/",
    summary: "外形或孔距相近的兼容品不等于可替换：阻尼、承重、孔位、调节范围、表面耐久、动感技术兼容性和保修责任可能不同。若项目指定 Blum，应按完整原厂 BOM 采购；如评估替代，须经设计/甲方书面批准，并对尺寸、满载运行、安全和售后分别做样品验证，不能混装后默认保修。",
    official: true,
    keywords: ["百隆兼容品", "原厂和国产区别", "替代百隆", "兼容铰链", "混装五金", "Blum原厂件", "original vs compatible", "替代风险"],
  },
  {
    id: "procurement-return-warranty-process",
    title: "采购：退货、换货与质保资料准备",
    url: "https://www.blum.com/cn/zh/contact/",
    summary: "退换和质保以购买渠道、地区条款、产品状态和安装证据为准。发现异常时保留完整产品号、批次、发票/订单、故障照片视频、安装环境及未改动状态；先向销售渠道登记，再按其流程送检或处理。定制、拆封、已安装或混装件可能影响可退条件，不能先自行拆修再主张原厂责任。",
    official: true,
    keywords: ["百隆质保", "百隆退货", "五金换货", "保修流程", "安装后能退吗", "售后需要什么", "warranty", "return policy"],
  },
] as const satisfies readonly OfficialSource[];

export const FALLBACK_SOURCE_IDS = [
  "product-catalogue",
  "product-configurator",
  "blum-contact",
  "easy-assembly",
  "quality-certification",
] as const;
